CREATE TABLE tableName
                        (    Student Roll Num	VARCHAR(512),
    Student Name	VARCHAR(512),
    StudentEmailID	VARCHAR(512),
    10th %	VARCHAR(512),
    12th %	VARCHAR(512),
    Current  % ( or CGPA) 	DOUBLE,
    College Name	VARCHAR(512),
    Department	VARCHAR(512),
    Current Semester	VARCHAR(512),
    WCF Mentor	VARCHAR(512),
    WCF E-Mail ID	VARCHAR(512),
    Batch	VARCHAR(512),
    Stream	VARCHAR(512),
    College Code	INT,
    Stream Code	VARCHAR(512),
    PBL_ID	VARCHAR(512),
    Tr.No	VARCHAR(512)
);

INSERT INTO tableName (Student Roll Num, Student Name, StudentEmailID, 10th %, 12th %, Current  % ( or CGPA) , College Name, Department, Current Semester, WCF Mentor, WCF E-Mail ID, Batch, Stream, College Code, Stream Code, PBL_ID, Tr.No) VALUES ('21AI008', 'A.Dharanidharan', 'dharanidharan.a564@gmail.com', '79', '84.9', '7.942', 'Nandha Engineering College, Erode', 'AI&DS', 'VI', 'A.Bharathi', 'bharathi.a@nandhaengg.org', 'Batch 1', 'JAVA Full Stack', '125', 'J', 'J_1250001', 'TNext_FY25_125_01_J');
INSERT INTO tableName (Student Roll Num, Student Name, StudentEmailID, 10th %, 12th %, Current  % ( or CGPA) , College Name, Department, Current Semester, WCF Mentor, WCF E-Mail ID, Batch, Stream, College Code, Stream Code, PBL_ID, Tr.No) VALUES ('21AI003', 'Chahana R', 'chahanaram@gmail.com', '78.8', '86.16', '8.101', 'Nandha Engineering College, Erode', 'AI&DS', 'VI', 'A.Bharathi', 'bharathi.a@nandhaengg.org', 'Batch 1', 'JAVA Full Stack', '125', 'J', 'J_1250002', 'TNext_FY25_125_01_J');
INSERT INTO tableName (Student Roll Num, Student Name, StudentEmailID, 10th %, 12th %, Current  % ( or CGPA) , College Name, Department, Current Semester, WCF Mentor, WCF E-Mail ID, Batch, Stream, College Code, Stream Code, PBL_ID, Tr.No) VALUES ('21AI004 ', 'Chinmaya. S', 'Chinmayasiva05@gmail.com', '80', '75', '7.9', 'Nandha Engineering College, Erode', 'AI&DS', 'VI', 'A.Bharathi', 'bharathi.a@nandhaengg.org', 'Batch 1', 'JAVA Full Stack', '125', 'J', 'J_1250003', 'TNext_FY25_125_01_J');
INSERT INTO tableName (Student Roll Num, Student Name, StudentEmailID, 10th %, 12th %, Current  % ( or CGPA) , College Name, Department, Current Semester, WCF Mentor, WCF E-Mail ID, Batch, Stream, College Code, Stream Code, PBL_ID, Tr.No) VALUES ('21AI007', 'Dhanush P', 'dhanush2k399@gmail.com', '78', '85', '7.73', 'Nandha Engineering College, Erode', 'AI&DS', 'VI', 'A.Bharathi', 'bharathi.a@nandhaengg.org', 'Batch 1', 'JAVA Full Stack', '125', 'J', 'J_1250004', 'TNext_FY25_125_01_J');
INSERT INTO tableName (Student Roll Num, Student Name, StudentEmailID, 10th %, 12th %, Current  % ( or CGPA) , College Name, Department, Current Semester, WCF Mentor, WCF E-Mail ID, Batch, Stream, College Code, Stream Code, PBL_ID, Tr.No) VALUES ('21AI010', 'Dineshkumar', 'dinesh2kmails@gmail.com', '88.8', '89', '8.15', 'Nandha Engineering College, Erode', 'AI&DS', 'VI', 'A.Bharathi', 'bharathi.a@nandhaengg.org', 'Batch 1', 'JAVA Full Stack', '125', 'J', 'J_1250005', 'TNext_FY25_125_01_J');
INSERT INTO tableName (Student Roll Num, Student Name, StudentEmailID, 10th %, 12th %, Current  % ( or CGPA) , College Name, Department, Current Semester, WCF Mentor, WCF E-Mail ID, Batch, Stream, College Code, Stream Code, PBL_ID, Tr.No) VALUES ('21AI013', 'Harini S', 'harinisekar1511@gmail.com', '86.6', '86.2', '8.316', 'Nandha Engineering College, Erode', 'AI&DS', 'VI', 'A.Bharathi', 'bharathi.a@nandhaengg.org', 'Batch 1', 'JAVA Full Stack', '125', 'J', 'J_1250006', 'TNext_FY25_125_01_J');
INSERT INTO tableName (Student Roll Num, Student Name, StudentEmailID, 10th %, 12th %, Current  % ( or CGPA) , College Name, Department, Current Semester, WCF Mentor, WCF E-Mail ID, Batch, Stream, College Code, Stream Code, PBL_ID, Tr.No) VALUES ('21AI014', 'Harish Babu R', 'harishbabu5435@gmail.com', '80', '87', '8', 'Nandha Engineering College, Erode', 'AI&DS', 'VI', 'A.Bharathi', 'bharathi.a@nandhaengg.org', 'Batch 1', 'JAVA Full Stack', '125', 'J', 'J_1250007', 'TNext_FY25_125_01_J');
INSERT INTO tableName (Student Roll Num, Student Name, StudentEmailID, 10th %, 12th %, Current  % ( or CGPA) , College Name, Department, Current Semester, WCF Mentor, WCF E-Mail ID, Batch, Stream, College Code, Stream Code, PBL_ID, Tr.No) VALUES ('21AI016', 'Jagadeeswaran Vp', 'jagadeeswaran8848@gmail.com', '86', '90', '8.7', 'Nandha Engineering College, Erode', 'AI&DS', 'VI', 'A.Bharathi', 'bharathi.a@nandhaengg.org', 'Batch 1', 'JAVA Full Stack', '125', 'J', 'J_1250008', 'TNext_FY25_125_01_J');
INSERT INTO tableName (Student Roll Num, Student Name, StudentEmailID, 10th %, 12th %, Current  % ( or CGPA) , College Name, Department, Current Semester, WCF Mentor, WCF E-Mail ID, Batch, Stream, College Code, Stream Code, PBL_ID, Tr.No) VALUES ('21AI020 ', 'Kirubasankar K R', 'kirubasankarkishore@gmail.com', '73', '79', '7.2', 'Nandha Engineering College, Erode', 'AI&DS', 'VI', 'A.Bharathi', 'bharathi.a@nandhaengg.org', 'Batch 1', 'JAVA Full Stack', '125', 'J', 'J_1250009', 'TNext_FY25_125_01_J');
INSERT INTO tableName (Student Roll Num, Student Name, StudentEmailID, 10th %, 12th %, Current  % ( or CGPA) , College Name, Department, Current Semester, WCF Mentor, WCF E-Mail ID, Batch, Stream, College Code, Stream Code, PBL_ID, Tr.No) VALUES ('21AI022', 'Kowsalya V', 'kowsalyavijayakumarkv@gmail.com', '77', '86', '7.7', 'Nandha Engineering College, Erode', 'AI&DS', 'VI', 'A.Bharathi', 'bharathi.a@nandhaengg.org', 'Batch 1', 'JAVA Full Stack', '125', 'J', 'J_1250010', 'TNext_FY25_125_01_J');
INSERT INTO tableName (Student Roll Num, Student Name, StudentEmailID, 10th %, 12th %, Current  % ( or CGPA) , College Name, Department, Current Semester, WCF Mentor, WCF E-Mail ID, Batch, Stream, College Code, Stream Code, PBL_ID, Tr.No) VALUES ('21AI006', 'M. Devadharshini', 'dharshinimuthukannan24@gmail.com', '76.4', '83.6', '8.22', 'Nandha Engineering College, Erode', 'AI&DS', 'VI', 'A.Bharathi', 'bharathi.a@nandhaengg.org', 'Batch 1', 'JAVA Full Stack', '125', 'J', 'J_1250011', 'TNext_FY25_125_01_J');
INSERT INTO tableName (Student Roll Num, Student Name, StudentEmailID, 10th %, 12th %, Current  % ( or CGPA) , College Name, Department, Current Semester, WCF Mentor, WCF E-Mail ID, Batch, Stream, College Code, Stream Code, PBL_ID, Tr.No) VALUES ('21AI025', 'Mohamed Assam.A', 'mohamedassam279@gmail.com', '75', '85', '7.1', 'Nandha Engineering College, Erode', 'AI&DS', 'VI', 'A.Bharathi', 'bharathi.a@nandhaengg.org', 'Batch 1', 'JAVA Full Stack', '125', 'J', 'J_1250012', 'TNext_FY25_125_01_J');
INSERT INTO tableName (Student Roll Num, Student Name, StudentEmailID, 10th %, 12th %, Current  % ( or CGPA) , College Name, Department, Current Semester, WCF Mentor, WCF E-Mail ID, Batch, Stream, College Code, Stream Code, PBL_ID, Tr.No) VALUES ('21AI026', 'Mohamed Haaris. A', 'mohamedhaarisa8@gmail.com', '61.2', '73.6', '7.114', 'Nandha Engineering College, Erode', 'AI&DS', 'VI', 'A.Bharathi', 'bharathi.a@nandhaengg.org', 'Batch 1', 'JAVA Full Stack', '125', 'J', 'J_1250013', 'TNext_FY25_125_01_J');
INSERT INTO tableName (Student Roll Num, Student Name, StudentEmailID, 10th %, 12th %, Current  % ( or CGPA) , College Name, Department, Current Semester, WCF Mentor, WCF E-Mail ID, Batch, Stream, College Code, Stream Code, PBL_ID, Tr.No) VALUES ('21AI032', 'Nivedhana S', 'nivedhanas10@gmail.com', '90', '92', '8.989', 'Nandha Engineering College, Erode', 'AI&DS', 'VI', 'A.Bharathi', 'bharathi.a@nandhaengg.org', 'Batch 1', 'JAVA Full Stack', '125', 'J', 'J_1250014', 'TNext_FY25_125_01_J');
INSERT INTO tableName (Student Roll Num, Student Name, StudentEmailID, 10th %, 12th %, Current  % ( or CGPA) , College Name, Department, Current Semester, WCF Mentor, WCF E-Mail ID, Batch, Stream, College Code, Stream Code, PBL_ID, Tr.No) VALUES ('21AI033', 'Poornavalli', 'ppoornavalli1@gmail.com', '82', '86', '8.816', 'Nandha Engineering College, Erode', 'AI&DS', 'VI', 'A.Bharathi', 'bharathi.a@nandhaengg.org', 'Batch 1', 'JAVA Full Stack', '125', 'J', 'J_1250015', 'TNext_FY25_125_01_J');
INSERT INTO tableName (Student Roll Num, Student Name, StudentEmailID, 10th %, 12th %, Current  % ( or CGPA) , College Name, Department, Current Semester, WCF Mentor, WCF E-Mail ID, Batch, Stream, College Code, Stream Code, PBL_ID, Tr.No) VALUES ('21AI034', 'Prabhakaran E', 'prabhakaran21ai@gmail.com', '67', '71', '7.4', 'Nandha Engineering College, Erode', 'AI&DS', 'VI', 'A.Bharathi', 'bharathi.a@nandhaengg.org', 'Batch 1', 'JAVA Full Stack', '125', 'J', 'J_1250016', 'TNext_FY25_125_01_J');
INSERT INTO tableName (Student Roll Num, Student Name, StudentEmailID, 10th %, 12th %, Current  % ( or CGPA) , College Name, Department, Current Semester, WCF Mentor, WCF E-Mail ID, Batch, Stream, College Code, Stream Code, PBL_ID, Tr.No) VALUES ('21AI035', 'Pradeepa S', 'pradeepaselvam319@gmail.com', '78.8', '83.3', '7.9', 'Nandha Engineering College, Erode', 'AI&DS', 'VI', 'A.Bharathi', 'bharathi.a@nandhaengg.org', 'Batch 1', 'JAVA Full Stack', '125', 'J', 'J_1250017', 'TNext_FY25_125_01_J');
INSERT INTO tableName (Student Roll Num, Student Name, StudentEmailID, 10th %, 12th %, Current  % ( or CGPA) , College Name, Department, Current Semester, WCF Mentor, WCF E-Mail ID, Batch, Stream, College Code, Stream Code, PBL_ID, Tr.No) VALUES ('21AI037', 'Rakesh. S', 'rakeshsidhu353@gmail.com', '77.6', '86', '7.8', 'Nandha Engineering College, Erode', 'AI&DS', 'VI', 'A.Bharathi', 'bharathi.a@nandhaengg.org', 'Batch 1', 'JAVA Full Stack', '125', 'J', 'J_1250018', 'TNext_FY25_125_01_J');
INSERT INTO tableName (Student Roll Num, Student Name, StudentEmailID, 10th %, 12th %, Current  % ( or CGPA) , College Name, Department, Current Semester, WCF Mentor, WCF E-Mail ID, Batch, Stream, College Code, Stream Code, PBL_ID, Tr.No) VALUES ('21AI038', 'Ramya B D', 'ramyadhana441@gmail.com', '93.4', '92', '9.17', 'Nandha Engineering College, Erode', 'AI&DS', 'VI', 'A.Bharathi', 'bharathi.a@nandhaengg.org', 'Batch 1', 'JAVA Full Stack', '125', 'J', 'J_1250019', 'TNext_FY25_125_01_J');
INSERT INTO tableName (Student Roll Num, Student Name, StudentEmailID, 10th %, 12th %, Current  % ( or CGPA) , College Name, Department, Current Semester, WCF Mentor, WCF E-Mail ID, Batch, Stream, College Code, Stream Code, PBL_ID, Tr.No) VALUES ('21AI039', 'Rithik P', 'rithikprabharithik@gmail.com', '71', '78', '6.9', 'Nandha Engineering College, Erode', 'AI&DS', 'VI', 'A.Bharathi', 'bharathi.a@nandhaengg.org', 'Batch 1', 'JAVA Full Stack', '125', 'J', 'J_1250020', 'TNext_FY25_125_01_J');
INSERT INTO tableName (Student Roll Num, Student Name, StudentEmailID, 10th %, 12th %, Current  % ( or CGPA) , College Name, Department, Current Semester, WCF Mentor, WCF E-Mail ID, Batch, Stream, College Code, Stream Code, PBL_ID, Tr.No) VALUES ('21AI049', 'S.Shiva Shri Shabhari', 'shivshri.s12@gmail.com', '82', '86', '8.5', 'Nandha Engineering College, Erode', 'AI&DS', 'VI', 'A.Bharathi', 'bharathi.a@nandhaengg.org', 'Batch 1', 'JAVA Full Stack', '125', 'J', 'J_1250021', 'TNext_FY25_125_01_J');
INSERT INTO tableName (Student Roll Num, Student Name, StudentEmailID, 10th %, 12th %, Current  % ( or CGPA) , College Name, Department, Current Semester, WCF Mentor, WCF E-Mail ID, Batch, Stream, College Code, Stream Code, PBL_ID, Tr.No) VALUES ('21AI040', 'Sakthisaravanan.T', 'sakthisaravana101@gmail.com', '60', '74', '7.1', 'Nandha Engineering College, Erode', 'AI&DS', 'VI', 'A.Bharathi', 'bharathi.a@nandhaengg.org', 'Batch 1', 'JAVA Full Stack', '125', 'J', 'J_1250022', 'TNext_FY25_125_01_J');
INSERT INTO tableName (Student Roll Num, Student Name, StudentEmailID, 10th %, 12th %, Current  % ( or CGPA) , College Name, Department, Current Semester, WCF Mentor, WCF E-Mail ID, Batch, Stream, College Code, Stream Code, PBL_ID, Tr.No) VALUES ('21AI042', 'Sandeep S D', 'sandeepsd245@gmail.com', '98', '89', '8.78', 'Nandha Engineering College, Erode', 'AI&DS', 'VI', 'A.Bharathi', 'bharathi.a@nandhaengg.org', 'Batch 1', 'JAVA Full Stack', '125', 'J', 'J_1250023', 'TNext_FY25_125_01_J');
INSERT INTO tableName (Student Roll Num, Student Name, StudentEmailID, 10th %, 12th %, Current  % ( or CGPA) , College Name, Department, Current Semester, WCF Mentor, WCF E-Mail ID, Batch, Stream, College Code, Stream Code, PBL_ID, Tr.No) VALUES ('21AI043', 'Sandhiya.K', 'sandhiyakumar575@gmail.com', '76.6', '79.2', '7.91', 'Nandha Engineering College, Erode', 'AI&DS', 'VI', 'A.Bharathi', 'bharathi.a@nandhaengg.org', 'Batch 1', 'JAVA Full Stack', '125', 'J', 'J_1250024', 'TNext_FY25_125_01_J');
INSERT INTO tableName (Student Roll Num, Student Name, StudentEmailID, 10th %, 12th %, Current  % ( or CGPA) , College Name, Department, Current Semester, WCF Mentor, WCF E-Mail ID, Batch, Stream, College Code, Stream Code, PBL_ID, Tr.No) VALUES ('21AI045', 'Sanjay Kanth G', 'sanjaykanthsk123@gmail.com', '72.5', '81.5', '7.62', 'Nandha Engineering College, Erode', 'AI&DS', 'VI', 'A.Bharathi', 'bharathi.a@nandhaengg.org', 'Batch 1', 'JAVA Full Stack', '125', 'J', 'J_1250025', 'TNext_FY25_125_01_J');
INSERT INTO tableName (Student Roll Num, Student Name, StudentEmailID, 10th %, 12th %, Current  % ( or CGPA) , College Name, Department, Current Semester, WCF Mentor, WCF E-Mail ID, Batch, Stream, College Code, Stream Code, PBL_ID, Tr.No) VALUES ('21AI046', 'Santhiya.R', 'santhiya26102004@gmail.com', '82', '86.96', '8.553', 'Nandha Engineering College, Erode', 'AI&DS', 'VI', 'A.Bharathi', 'bharathi.a@nandhaengg.org', 'Batch 1', 'JAVA Full Stack', '125', 'J', 'J_1250026', 'TNext_FY25_125_01_J');
INSERT INTO tableName (Student Roll Num, Student Name, StudentEmailID, 10th %, 12th %, Current  % ( or CGPA) , College Name, Department, Current Semester, WCF Mentor, WCF E-Mail ID, Batch, Stream, College Code, Stream Code, PBL_ID, Tr.No) VALUES ('21AI047', 'Saravana Kumar D', 'selvasaravanan211@gmail.com', '74', '81.9', '7.7', 'Nandha Engineering College, Erode', 'AI&DS', 'VI', 'A.Bharathi', 'bharathi.a@nandhaengg.org', 'Batch 1', 'JAVA Full Stack', '125', 'J', 'J_1250027', 'TNext_FY25_125_01_J');
INSERT INTO tableName (Student Roll Num, Student Name, StudentEmailID, 10th %, 12th %, Current  % ( or CGPA) , College Name, Department, Current Semester, WCF Mentor, WCF E-Mail ID, Batch, Stream, College Code, Stream Code, PBL_ID, Tr.No) VALUES ('21AI051', 'Shri Keerthana R', 'shrikeerthanarameshkumar@gmail.com', '83.6', '87.3', '8.22', 'Nandha Engineering College, Erode', 'AI&DS', 'VI', 'A.Bharathi', 'bharathi.a@nandhaengg.org', 'Batch 1', 'JAVA Full Stack', '125', 'J', 'J_1250028', 'TNext_FY25_125_01_J');
INSERT INTO tableName (Student Roll Num, Student Name, StudentEmailID, 10th %, 12th %, Current  % ( or CGPA) , College Name, Department, Current Semester, WCF Mentor, WCF E-Mail ID, Batch, Stream, College Code, Stream Code, PBL_ID, Tr.No) VALUES ('21AI053', 'Srisanthosh K', 'srisanthoshtowork@gmail.com', '79.2', '84.45', '7.65', 'Nandha Engineering College, Erode', 'AI&DS', 'VI', 'A.Bharathi', 'bharathi.a@nandhaengg.org', 'Batch 1', 'JAVA Full Stack', '125', 'J', 'J_1250029', 'TNext_FY25_125_01_J');
INSERT INTO tableName (Student Roll Num, Student Name, StudentEmailID, 10th %, 12th %, Current  % ( or CGPA) , College Name, Department, Current Semester, WCF Mentor, WCF E-Mail ID, Batch, Stream, College Code, Stream Code, PBL_ID, Tr.No) VALUES ('21AI055', 'Sudhakar.D', 'sujusudhakar44@gmail.com', '77.8', '87.5', '7.735', 'Nandha Engineering College, Erode', 'AI&DS', 'VI', 'A.Bharathi', 'bharathi.a@nandhaengg.org', 'Batch 1', 'JAVA Full Stack', '125', 'J', 'J_1250030', 'TNext_FY25_125_01_J');
INSERT INTO tableName (Student Roll Num, Student Name, StudentEmailID, 10th %, 12th %, Current  % ( or CGPA) , College Name, Department, Current Semester, WCF Mentor, WCF E-Mail ID, Batch, Stream, College Code, Stream Code, PBL_ID, Tr.No) VALUES ('21AI001', 'V Balakrishnan', 'shibhibala07@gmail.com', '83', '89', '8', 'Nandha Engineering College, Erode', 'AI&DS', 'VI', 'A.Bharathi', 'bharathi.a@nandhaengg.org', 'Batch 1', 'JAVA Full Stack', '125', 'J', 'J_1250031', 'TNext_FY25_125_01_J');
INSERT INTO tableName (Student Roll Num, Student Name, StudentEmailID, 10th %, 12th %, Current  % ( or CGPA) , College Name, Department, Current Semester, WCF Mentor, WCF E-Mail ID, Batch, Stream, College Code, Stream Code, PBL_ID, Tr.No) VALUES ('21AI058', 'Yogesh M V', 'yogeshmv744@gmail.com', '82.2', '85.9', '8.73', 'Nandha Engineering College, Erode', 'AI&DS', 'VI', 'A.Bharathi', 'bharathi.a@nandhaengg.org', 'Batch 1', 'JAVA Full Stack', '125', 'J', 'J_1250032', 'TNext_FY25_125_01_J');
INSERT INTO tableName (Student Roll Num, Student Name, StudentEmailID, 10th %, 12th %, Current  % ( or CGPA) , College Name, Department, Current Semester, WCF Mentor, WCF E-Mail ID, Batch, Stream, College Code, Stream Code, PBL_ID, Tr.No) VALUES ('21CS096', 'A.Suresh', 'sureshalakesan2004@gmail.com', '63', '74', '7.2', 'Nandha Engineering College, Erode', 'CSE', 'VI', 'J.Radha', 'radha@nandhaengg.org', '2', 'JAVA Full Stack', '125', 'J', 'J_1250033', 'TNext_FY25_125_01_J');
INSERT INTO tableName (Student Roll Num, Student Name, StudentEmailID, 10th %, 12th %, Current  % ( or CGPA) , College Name, Department, Current Semester, WCF Mentor, WCF E-Mail ID, Batch, Stream, College Code, Stream Code, PBL_ID, Tr.No) VALUES ('21CS001', 'Ajay S', 's.ajay15082002@gmail.com', '93.4', '90.3383', '8.977', 'Nandha Engineering College, Erode', 'CSE', 'VI', 'A.Bharathi', 'bharathi.a@nandhaengg.org', 'Batch 1', 'JAVA Full Stack', '125', 'J', 'J_1250034', 'TNext_FY25_125_01_J');
INSERT INTO tableName (Student Roll Num, Student Name, StudentEmailID, 10th %, 12th %, Current  % ( or CGPA) , College Name, Department, Current Semester, WCF Mentor, WCF E-Mail ID, Batch, Stream, College Code, Stream Code, PBL_ID, Tr.No) VALUES ('21CSL01', 'Ajith M', 'ajiajith0245@gmail.com', '88.2', '91.3', '7.7', 'Nandha Engineering College, Erode', 'CSE', 'VI', 'J.Radha', 'radha@nandhaengg.org', '2', 'JAVA Full Stack', '125', 'J', 'J_1250035', 'TNext_FY25_125_01_J');
INSERT INTO tableName (Student Roll Num, Student Name, StudentEmailID, 10th %, 12th %, Current  % ( or CGPA) , College Name, Department, Current Semester, WCF Mentor, WCF E-Mail ID, Batch, Stream, College Code, Stream Code, PBL_ID, Tr.No) VALUES ('21CS002', 'Anushobini S', 'sanushobini@gmail.com', '84', '88.33', '8.21', 'Nandha Engineering College, Erode', 'CSE', 'VI', 'A.Bharathi', 'bharathi.a@nandhaengg.org', 'Batch 1', 'JAVA Full Stack', '125', 'J', 'J_1250036', 'TNext_FY25_125_01_J');
INSERT INTO tableName (Student Roll Num, Student Name, StudentEmailID, 10th %, 12th %, Current  % ( or CGPA) , College Name, Department, Current Semester, WCF Mentor, WCF E-Mail ID, Batch, Stream, College Code, Stream Code, PBL_ID, Tr.No) VALUES ('21CS004', 'Ashokkumar S', 'ashoksekar308@gmail.com', '70.2', '76.83', '7.006', 'Nandha Engineering College, Erode', 'CSE', 'VI', 'A.Bharathi', 'bharathi.a@nandhaengg.org', 'Batch 1', 'JAVA Full Stack', '125', 'J', 'J_1250037', 'TNext_FY25_125_01_J');
INSERT INTO tableName (Student Roll Num, Student Name, StudentEmailID, 10th %, 12th %, Current  % ( or CGPA) , College Name, Department, Current Semester, WCF Mentor, WCF E-Mail ID, Batch, Stream, College Code, Stream Code, PBL_ID, Tr.No) VALUES ('21CS007', 'Bharun D M', 'bharundm@gmail.com', '75', '81.03', '7.8', 'Nandha Engineering College, Erode', 'CSE', 'VI', 'A.Bharathi', 'bharathi.a@nandhaengg.org', 'Batch 1', 'JAVA Full Stack', '125', 'J', 'J_1250038', 'TNext_FY25_125_01_J');
INSERT INTO tableName (Student Roll Num, Student Name, StudentEmailID, 10th %, 12th %, Current  % ( or CGPA) , College Name, Department, Current Semester, WCF Mentor, WCF E-Mail ID, Batch, Stream, College Code, Stream Code, PBL_ID, Tr.No) VALUES ('21CS008', 'Boobalan.D', 'boobalanduraisamy457@gmail.com', '74.6', '82.66', '7.9', 'Nandha Engineering College, Erode', 'CSE', 'VI', 'A.Bharathi', 'bharathi.a@nandhaengg.org', 'Batch 1', 'JAVA Full Stack', '125', 'J', 'J_1250039', 'TNext_FY25_125_01_J');
INSERT INTO tableName (Student Roll Num, Student Name, StudentEmailID, 10th %, 12th %, Current  % ( or CGPA) , College Name, Department, Current Semester, WCF Mentor, WCF E-Mail ID, Batch, Stream, College Code, Stream Code, PBL_ID, Tr.No) VALUES ('21CS009', 'Chanchalhas.V', 'iamchanchalhas@gmail.com', '74.4', '84.4', '7.8', 'Nandha Engineering College, Erode', 'CSE', 'VI', 'A.Bharathi', 'bharathi.a@nandhaengg.org', 'Batch 1', 'JAVA Full Stack', '125', 'J', 'J_1250040', 'TNext_FY25_125_01_J');
INSERT INTO tableName (Student Roll Num, Student Name, StudentEmailID, 10th %, 12th %, Current  % ( or CGPA) , College Name, Department, Current Semester, WCF Mentor, WCF E-Mail ID, Batch, Stream, College Code, Stream Code, PBL_ID, Tr.No) VALUES ('21CS010', 'Christopher R', 'christopherfranklin0403@gmail.com', '95.4', '96', '9.7', 'Nandha Engineering College, Erode', 'CSE', 'VI', 'A.Bharathi', 'bharathi.a@nandhaengg.org', 'Batch 1', 'JAVA Full Stack', '125', 'J', 'J_1250041', 'TNext_FY25_125_01_J');
INSERT INTO tableName (Student Roll Num, Student Name, StudentEmailID, 10th %, 12th %, Current  % ( or CGPA) , College Name, Department, Current Semester, WCF Mentor, WCF E-Mail ID, Batch, Stream, College Code, Stream Code, PBL_ID, Tr.No) VALUES ('21CS011', 'Darsini K', 'kdarsinikdarsini@gmail.com', '78.8', '85', '8.6', 'Nandha Engineering College, Erode', 'CSE', 'VI', 'J.Radha', 'radha@nandhaengg.org', '2', 'JAVA Full Stack', '125', 'J', 'J_1250042', 'TNext_FY25_125_01_J');
INSERT INTO tableName (Student Roll Num, Student Name, StudentEmailID, 10th %, 12th %, Current  % ( or CGPA) , College Name, Department, Current Semester, WCF Mentor, WCF E-Mail ID, Batch, Stream, College Code, Stream Code, PBL_ID, Tr.No) VALUES ('21CS012', 'Devadharshini G', 'devadharshini4453@gmail.com', '76.8', '84.5', '7.6', 'Nandha Engineering College, Erode', 'CSE', 'VI', 'J.Radha', 'radha@nandhaengg.org', '2', 'JAVA Full Stack', '125', 'J', 'J_1250043', 'TNext_FY25_125_01_J');
INSERT INTO tableName (Student Roll Num, Student Name, StudentEmailID, 10th %, 12th %, Current  % ( or CGPA) , College Name, Department, Current Semester, WCF Mentor, WCF E-Mail ID, Batch, Stream, College Code, Stream Code, PBL_ID, Tr.No) VALUES ('21CS013', 'Devendhiran S', 'devendhiran013@gmail.com', '74.4', '83.16', '8.1', 'Nandha Engineering College, Erode', 'CSE', 'VI', 'J.Radha', 'radha@nandhaengg.org', '2', 'JAVA Full Stack', '125', 'J', 'J_1250044', 'TNext_FY25_125_01_J');
INSERT INTO tableName (Student Roll Num, Student Name, StudentEmailID, 10th %, 12th %, Current  % ( or CGPA) , College Name, Department, Current Semester, WCF Mentor, WCF E-Mail ID, Batch, Stream, College Code, Stream Code, PBL_ID, Tr.No) VALUES ('21CS014', 'Dhaneswara V', 'dhaneswaravaratharaj@gmail.com', '88.6', '88.16', '8.08', 'Nandha Engineering College, Erode', 'CSE', 'VI', 'J.Radha', 'radha@nandhaengg.org', '2', 'JAVA Full Stack', '125', 'J', 'J_1250045', 'TNext_FY25_125_01_J');
INSERT INTO tableName (Student Roll Num, Student Name, StudentEmailID, 10th %, 12th %, Current  % ( or CGPA) , College Name, Department, Current Semester, WCF Mentor, WCF E-Mail ID, Batch, Stream, College Code, Stream Code, PBL_ID, Tr.No) VALUES ('21CS015', 'Dhanish S', 'sdhanish080@gmail.com', '80.6', '88.66', '8.7', 'Nandha Engineering College, Erode', 'CSE', 'VI', 'J.Radha', 'radha@nandhaengg.org', '2', 'JAVA Full Stack', '125', 'J', 'J_1250046', 'TNext_FY25_125_01_J');
INSERT INTO tableName (Student Roll Num, Student Name, StudentEmailID, 10th %, 12th %, Current  % ( or CGPA) , College Name, Department, Current Semester, WCF Mentor, WCF E-Mail ID, Batch, Stream, College Code, Stream Code, PBL_ID, Tr.No) VALUES ('21CS017', 'Dinesh M', 'danamdinesh11@gmail.com', '89.6', '90.8', '8.787', 'Nandha Engineering College, Erode', 'CSE', 'VI', 'J.Radha', 'radha@nandhaengg.org', '2', 'JAVA Full Stack', '125', 'J', 'J_1250047', 'TNext_FY25_125_01_J');
INSERT INTO tableName (Student Roll Num, Student Name, StudentEmailID, 10th %, 12th %, Current  % ( or CGPA) , College Name, Department, Current Semester, WCF Mentor, WCF E-Mail ID, Batch, Stream, College Code, Stream Code, PBL_ID, Tr.No) VALUES ('21CS016', 'Dinesh R', 'dineshvindhiya006@gmail.com', '69', '77', '7.4', 'Nandha Engineering College, Erode', 'CSE', 'VI', 'J.Radha', 'radha@nandhaengg.org', '2', 'JAVA Full Stack', '125', 'J', 'J_1250048', 'TNext_FY25_125_01_J');
INSERT INTO tableName (Student Roll Num, Student Name, StudentEmailID, 10th %, 12th %, Current  % ( or CGPA) , College Name, Department, Current Semester, WCF Mentor, WCF E-Mail ID, Batch, Stream, College Code, Stream Code, PBL_ID, Tr.No) VALUES ('21CS018', 'Dusyanth N P', 'dusyanth05@gmail.com', '64.4', '78.16', '7.5', 'Nandha Engineering College, Erode', 'CSE', 'VI', 'J.Radha', 'radha@nandhaengg.org', '2', 'JAVA Full Stack', '125', 'J', 'J_1250049', 'TNext_FY25_125_01_J');
INSERT INTO tableName (Student Roll Num, Student Name, StudentEmailID, 10th %, 12th %, Current  % ( or CGPA) , College Name, Department, Current Semester, WCF Mentor, WCF E-Mail ID, Batch, Stream, College Code, Stream Code, PBL_ID, Tr.No) VALUES ('21CS019', 'Elamathi .T.M', 'tmelamathi23@gmail.com', '79.2', '85.44', '8.3', 'Nandha Engineering College, Erode', 'CSE', 'VI', 'J.Radha', 'radha@nandhaengg.org', '2', 'JAVA Full Stack', '125', 'J', 'J_1250050', 'TNext_FY25_125_01_J');
INSERT INTO tableName (Student Roll Num, Student Name, StudentEmailID, 10th %, 12th %, Current  % ( or CGPA) , College Name, Department, Current Semester, WCF Mentor, WCF E-Mail ID, Batch, Stream, College Code, Stream Code, PBL_ID, Tr.No) VALUES ('21CS021', 'Girija Gayathri M', 'girijagayu2003@gmail.com', '82', '86.74', '8.7', 'Nandha Engineering College, Erode', 'CSE', 'VI', 'J.Radha', 'radha@nandhaengg.org', '2', 'JAVA Full Stack', '125', 'J', 'J_1250051', 'TNext_FY25_125_01_J');
INSERT INTO tableName (Student Roll Num, Student Name, StudentEmailID, 10th %, 12th %, Current  % ( or CGPA) , College Name, Department, Current Semester, WCF Mentor, WCF E-Mail ID, Batch, Stream, College Code, Stream Code, PBL_ID, Tr.No) VALUES ('21CS022', 'Gobinath G', 'ggobinath55gobi@gmail.com', '77.8', '86.81', '8.5', 'Nandha Engineering College, Erode', 'CSE', 'VI', 'J.Radha', 'radha@nandhaengg.org', '2', 'JAVA Full Stack', '125', 'J', 'J_1250052', 'TNext_FY25_125_01_J');
INSERT INTO tableName (Student Roll Num, Student Name, StudentEmailID, 10th %, 12th %, Current  % ( or CGPA) , College Name, Department, Current Semester, WCF Mentor, WCF E-Mail ID, Batch, Stream, College Code, Stream Code, PBL_ID, Tr.No) VALUES ('21CS023', 'Gokul G', 'gkmarsil2003@gmail.com', '76.6', '82.8', '7.5', 'Nandha Engineering College, Erode', 'CSE', 'VI', 'J.Radha', 'radha@nandhaengg.org', '2', 'JAVA Full Stack', '125', 'J', 'J_1250053', 'TNext_FY25_125_01_J');
INSERT INTO tableName (Student Roll Num, Student Name, StudentEmailID, 10th %, 12th %, Current  % ( or CGPA) , College Name, Department, Current Semester, WCF Mentor, WCF E-Mail ID, Batch, Stream, College Code, Stream Code, PBL_ID, Tr.No) VALUES ('21CS024', 'Gokul.K', 'gokulbecse232004@gmail.com', '64', '76.6', '8.3', 'Nandha Engineering College, Erode', 'CSE', 'VI', 'J.Radha', 'radha@nandhaengg.org', '2', 'JAVA Full Stack', '125', 'J', 'J_1250054', 'TNext_FY25_125_01_J');
INSERT INTO tableName (Student Roll Num, Student Name, StudentEmailID, 10th %, 12th %, Current  % ( or CGPA) , College Name, Department, Current Semester, WCF Mentor, WCF E-Mail ID, Batch, Stream, College Code, Stream Code, PBL_ID, Tr.No) VALUES ('21CS025', 'Gomathy G', 'ggomathy96@gmail.com', '70.4', '82.16', '9.3427', 'Nandha Engineering College, Erode', 'CSE', 'VI', 'J.Radha', 'radha@nandhaengg.org', '2', 'JAVA Full Stack', '125', 'J', 'J_1250055', 'TNext_FY25_125_01_J');
INSERT INTO tableName (Student Roll Num, Student Name, StudentEmailID, 10th %, 12th %, Current  % ( or CGPA) , College Name, Department, Current Semester, WCF Mentor, WCF E-Mail ID, Batch, Stream, College Code, Stream Code, PBL_ID, Tr.No) VALUES ('21CS028', 'Hariharan M', 'hariharan33221@gmail.com', '76.2', '88.49', '8.7', 'Nandha Engineering College, Erode', 'CSE', 'VI', 'J.Radha', 'radha@nandhaengg.org', '2', 'JAVA Full Stack', '125', 'J', 'J_1250056', 'TNext_FY25_125_01_J');
INSERT INTO tableName (Student Roll Num, Student Name, StudentEmailID, 10th %, 12th %, Current  % ( or CGPA) , College Name, Department, Current Semester, WCF Mentor, WCF E-Mail ID, Batch, Stream, College Code, Stream Code, PBL_ID, Tr.No) VALUES ('21CS029', 'Harini V', 'harinivenkatesan168@gmail.com', '84.4', '84.99', '8.46', 'Nandha Engineering College, Erode', 'CSE', 'VI', 'J.Radha', 'radha@nandhaengg.org', '2', 'JAVA Full Stack', '125', 'J', 'J_1250057', 'TNext_FY25_125_01_J');
INSERT INTO tableName (Student Roll Num, Student Name, StudentEmailID, 10th %, 12th %, Current  % ( or CGPA) , College Name, Department, Current Semester, WCF Mentor, WCF E-Mail ID, Batch, Stream, College Code, Stream Code, PBL_ID, Tr.No) VALUES ('21CS031', 'Hemanath P', 'dharanishhemanath@gmail.com', '84.2', '84.4', '7.8', 'Nandha Engineering College, Erode', 'CSE', 'VI', 'J.Radha', 'radha@nandhaengg.org', '2', 'JAVA Full Stack', '125', 'J', 'J_1250058', 'TNext_FY25_125_01_J');
INSERT INTO tableName (Student Roll Num, Student Name, StudentEmailID, 10th %, 12th %, Current  % ( or CGPA) , College Name, Department, Current Semester, WCF Mentor, WCF E-Mail ID, Batch, Stream, College Code, Stream Code, PBL_ID, Tr.No) VALUES ('21CS032', 'Janani', 'jananiarunachalam03@gmail.com', '85.8', '90.3', '7.6', 'Nandha Engineering College, Erode', 'CSE', 'VI', 'J.Radha', 'radha@nandhaengg.org', '2', 'JAVA Full Stack', '125', 'J', 'J_1250059', 'TNext_FY25_125_01_J');
INSERT INTO tableName (Student Roll Num, Student Name, StudentEmailID, 10th %, 12th %, Current  % ( or CGPA) , College Name, Department, Current Semester, WCF Mentor, WCF E-Mail ID, Batch, Stream, College Code, Stream Code, PBL_ID, Tr.No) VALUES ('21CS034', 'Jeevabharathi', 'vijayjeeva445925@gmail.com', '84.8', '88.13', '8.352', 'Nandha Engineering College, Erode', 'CSE', 'VI', 'J.Radha', 'radha@nandhaengg.org', '2', 'JAVA Full Stack', '125', 'J', 'J_1250060', 'TNext_FY25_125_01_J');
INSERT INTO tableName (Student Roll Num, Student Name, StudentEmailID, 10th %, 12th %, Current  % ( or CGPA) , College Name, Department, Current Semester, WCF Mentor, WCF E-Mail ID, Batch, Stream, College Code, Stream Code, PBL_ID, Tr.No) VALUES ('21CS035', 'Jeyabharathi.P', 'jeyabharathipounraj@gmail.com', '67.6', '81.95', '8.2', 'Nandha Engineering College, Erode', 'CSE', 'VI', 'J.Radha', 'radha@nandhaengg.org', '2', 'JAVA Full Stack', '125', 'J', 'J_1250061', 'TNext_FY25_125_01_J');
INSERT INTO tableName (Student Roll Num, Student Name, StudentEmailID, 10th %, 12th %, Current  % ( or CGPA) , College Name, Department, Current Semester, WCF Mentor, WCF E-Mail ID, Batch, Stream, College Code, Stream Code, PBL_ID, Tr.No) VALUES ('21CS006', 'K M Barani Kumar', 'baranipeter11@gmail.com', '70.8', '81.1', '8', 'Nandha Engineering College, Erode', 'CSE', 'VI', 'A.Bharathi', 'bharathi.a@nandhaengg.org', 'Batch 1', 'JAVA Full Stack', '125', 'J', 'J_1250062', 'TNext_FY25_125_01_J');
INSERT INTO tableName (Student Roll Num, Student Name, StudentEmailID, 10th %, 12th %, Current  % ( or CGPA) , College Name, Department, Current Semester, WCF Mentor, WCF E-Mail ID, Batch, Stream, College Code, Stream Code, PBL_ID, Tr.No) VALUES ('21CS119', 'K.S.Yuva Surya', 'yuvasuryay2d@gmail.com', '71.4', '78.32', '7.8', 'Nandha Engineering College, Erode', 'CSE', 'VI', 'J.Radha', 'radha@nandhaengg.org', '2', 'JAVA Full Stack', '125', 'J', 'J_1250063', 'TNext_FY25_125_01_J');
INSERT INTO tableName (Student Roll Num, Student Name, StudentEmailID, 10th %, 12th %, Current  % ( or CGPA) , College Name, Department, Current Semester, WCF Mentor, WCF E-Mail ID, Batch, Stream, College Code, Stream Code, PBL_ID, Tr.No) VALUES ('21CS036', 'Kaarthik.K.S', 'kskaarthik039@gmail.com', '82', '88', '7.5', 'Nandha Engineering College, Erode', 'CSE', 'VI', 'J.Radha', 'radha@nandhaengg.org', '2', 'JAVA Full Stack', '125', 'J', 'J_1250064', 'TNext_FY25_125_01_J');
INSERT INTO tableName (Student Roll Num, Student Name, StudentEmailID, 10th %, 12th %, Current  % ( or CGPA) , College Name, Department, Current Semester, WCF Mentor, WCF E-Mail ID, Batch, Stream, College Code, Stream Code, PBL_ID, Tr.No) VALUES ('21CS040', 'Karthikeyan N', 'karthikeyan435552@gmail.com', '87', '91.99', '8.8714', 'Nandha Engineering College, Erode', 'CSE', 'VI', 'J.Radha', 'radha@nandhaengg.org', '2', 'JAVA Full Stack', '125', 'J', 'J_1250065', 'TNext_FY25_125_01_J');
INSERT INTO tableName (Student Roll Num, Student Name, StudentEmailID, 10th %, 12th %, Current  % ( or CGPA) , College Name, Department, Current Semester, WCF Mentor, WCF E-Mail ID, Batch, Stream, College Code, Stream Code, PBL_ID, Tr.No) VALUES ('21CS044', 'Kavinsubash K R', 'kavinramasamy2003@gmail.com', '88.4', '71.5', '9.69', 'Nandha Engineering College, Erode', 'CSE', 'VI', 'J.Radha', 'radha@nandhaengg.org', '2', 'JAVA Full Stack', '125', 'J', 'J_1250066', 'TNext_FY25_125_01_J');
INSERT INTO tableName (Student Roll Num, Student Name, StudentEmailID, 10th %, 12th %, Current  % ( or CGPA) , College Name, Department, Current Semester, WCF Mentor, WCF E-Mail ID, Batch, Stream, College Code, Stream Code, PBL_ID, Tr.No) VALUES ('21CS046', 'Kishor M V', 'kishormuthu2@gmail.com', '88.2', '87.56', '8.6', 'Nandha Engineering College, Erode', 'CSE', 'VI', 'J.Radha', 'radha@nandhaengg.org', '2', 'JAVA Full Stack', '125', 'J', 'J_1250067', 'TNext_FY25_125_01_J');
INSERT INTO tableName (Student Roll Num, Student Name, StudentEmailID, 10th %, 12th %, Current  % ( or CGPA) , College Name, Department, Current Semester, WCF Mentor, WCF E-Mail ID, Batch, Stream, College Code, Stream Code, PBL_ID, Tr.No) VALUES ('21CS003', 'L.K.Ashok', 'ashokb2k@gmail.com', '77.2', '83.5', '7.6', 'Nandha Engineering College, Erode', 'CSE', 'VI', 'A.Bharathi', 'bharathi.a@nandhaengg.org', 'Batch 1', 'JAVA Full Stack', '125', 'J', 'J_1250068', 'TNext_FY25_125_01_J');
INSERT INTO tableName (Student Roll Num, Student Name, StudentEmailID, 10th %, 12th %, Current  % ( or CGPA) , College Name, Department, Current Semester, WCF Mentor, WCF E-Mail ID, Batch, Stream, College Code, Stream Code, PBL_ID, Tr.No) VALUES ('21CS047', 'Lakshana S', 'lakshanas984@gmail.com', '90.4', '91.5', '8.2', 'Nandha Engineering College, Erode', 'CSE', 'VI', 'J.Radha', 'radha@nandhaengg.org', '2', 'JAVA Full Stack', '125', 'J', 'J_1250069', 'TNext_FY25_125_01_J');
INSERT INTO tableName (Student Roll Num, Student Name, StudentEmailID, 10th %, 12th %, Current  % ( or CGPA) , College Name, Department, Current Semester, WCF Mentor, WCF E-Mail ID, Batch, Stream, College Code, Stream Code, PBL_ID, Tr.No) VALUES ('21CS048', 'Lathiga L', 'lathigal5@gmail.com', '87.6', '89.71', '8.1975', 'Nandha Engineering College, Erode', 'CSE', 'VI', 'J.Radha', 'radha@nandhaengg.org', '2', 'JAVA Full Stack', '125', 'J', 'J_1250070', 'TNext_FY25_125_01_J');
INSERT INTO tableName (Student Roll Num, Student Name, StudentEmailID, 10th %, 12th %, Current  % ( or CGPA) , College Name, Department, Current Semester, WCF Mentor, WCF E-Mail ID, Batch, Stream, College Code, Stream Code, PBL_ID, Tr.No) VALUES ('21CS049', 'Loganayagam.R', 'loganayagam3@gmail.com', '79.3', '83', '7.3', 'Nandha Engineering College, Erode', 'CSE', 'VI', 'J.Radha', 'radha@nandhaengg.org', '2', 'JAVA Full Stack', '125', 'J', 'J_1250071', 'TNext_FY25_125_01_J');
INSERT INTO tableName (Student Roll Num, Student Name, StudentEmailID, 10th %, 12th %, Current  % ( or CGPA) , College Name, Department, Current Semester, WCF Mentor, WCF E-Mail ID, Batch, Stream, College Code, Stream Code, PBL_ID, Tr.No) VALUES ('21CS050', 'Madheswaran M', '92madheswaran2004@gmail.com', '71.2', '78.68', '8.19', 'Nandha Engineering College, Erode', 'CSE', 'VI', 'J.Radha', 'radha@nandhaengg.org', '2', 'JAVA Full Stack', '125', 'J', 'J_1250072', 'TNext_FY25_125_01_J');
INSERT INTO tableName (Student Roll Num, Student Name, StudentEmailID, 10th %, 12th %, Current  % ( or CGPA) , College Name, Department, Current Semester, WCF Mentor, WCF E-Mail ID, Batch, Stream, College Code, Stream Code, PBL_ID, Tr.No) VALUES ('21CS051', 'Manoj V', 'manojkapildev3521@gmail.com', '71.8', '81.965', '8.0826', 'Nandha Engineering College, Erode', 'CSE', 'VI', 'J.Radha', 'radha@nandhaengg.org', '2', 'JAVA Full Stack', '125', 'J', 'J_1250073', 'TNext_FY25_125_01_J');
INSERT INTO tableName (Student Roll Num, Student Name, StudentEmailID, 10th %, 12th %, Current  % ( or CGPA) , College Name, Department, Current Semester, WCF Mentor, WCF E-Mail ID, Batch, Stream, College Code, Stream Code, PBL_ID, Tr.No) VALUES ('21CS054', 'Mathu Kumar G', 'mathukumar735@gmail.com', '78.2', '86.833', '8.1', 'Nandha Engineering College, Erode', 'CSE', 'VI', 'J.Radha', 'radha@nandhaengg.org', '2', 'JAVA Full Stack', '125', 'J', 'J_1250074', 'TNext_FY25_125_01_J');
INSERT INTO tableName (Student Roll Num, Student Name, StudentEmailID, 10th %, 12th %, Current  % ( or CGPA) , College Name, Department, Current Semester, WCF Mentor, WCF E-Mail ID, Batch, Stream, College Code, Stream Code, PBL_ID, Tr.No) VALUES ('21CS055', 'Meiyazhagan Bs', 'bsmeiyazhagan003@gmail.com', '61.2', '71.8', '7.5', 'Nandha Engineering College, Erode', 'CSE', 'VI', 'J.Radha', 'radha@nandhaengg.org', '2', 'JAVA Full Stack', '125', 'J', 'J_1250075', 'TNext_FY25_125_01_J');
INSERT INTO tableName (Student Roll Num, Student Name, StudentEmailID, 10th %, 12th %, Current  % ( or CGPA) , College Name, Department, Current Semester, WCF Mentor, WCF E-Mail ID, Batch, Stream, College Code, Stream Code, PBL_ID, Tr.No) VALUES ('21CS056', 'Mohammed Naveeth.P', 'mohammednaveeth143@gmail.com', '78.2', '83.43', '7.5', 'Nandha Engineering College, Erode', 'CSE', 'VI', 'J.Radha', 'radha@nandhaengg.org', '2', 'JAVA Full Stack', '125', 'J', 'J_1250076', 'TNext_FY25_125_01_J');
INSERT INTO tableName (Student Roll Num, Student Name, StudentEmailID, 10th %, 12th %, Current  % ( or CGPA) , College Name, Department, Current Semester, WCF Mentor, WCF E-Mail ID, Batch, Stream, College Code, Stream Code, PBL_ID, Tr.No) VALUES ('21CS057', 'Monisha R M', 'mmonishamarisamy@gmail.com', '86.6', '88.58', '8.6', 'Nandha Engineering College, Erode', 'CSE', 'VI', 'J.Radha', 'radha@nandhaengg.org', '2', 'JAVA Full Stack', '125', 'J', 'J_1250077', 'TNext_FY25_125_01_J');
INSERT INTO tableName (Student Roll Num, Student Name, StudentEmailID, 10th %, 12th %, Current  % ( or CGPA) , College Name, Department, Current Semester, WCF Mentor, WCF E-Mail ID, Batch, Stream, College Code, Stream Code, PBL_ID, Tr.No) VALUES ('21CS058', 'Nagulkumar P', 'nagulp2003@gmail.com', '85', '90.615', '8.263', 'Nandha Engineering College, Erode', 'CSE', 'VI', 'J.Radha', 'radha@nandhaengg.org', '2', 'JAVA Full Stack', '125', 'J', 'J_1250078', 'TNext_FY25_125_01_J');
INSERT INTO tableName (Student Roll Num, Student Name, StudentEmailID, 10th %, 12th %, Current  % ( or CGPA) , College Name, Department, Current Semester, WCF Mentor, WCF E-Mail ID, Batch, Stream, College Code, Stream Code, PBL_ID, Tr.No) VALUES ('21CS060', 'Naveen Prabhu S', '2004naveenprabhu@gmail.com', '87.8', '91.96', '8.6', 'Nandha Engineering College, Erode', 'CSE', 'VI', 'J.Radha', 'radha@nandhaengg.org', '2', 'JAVA Full Stack', '125', 'J', 'J_1250079', 'TNext_FY25_125_01_J');
INSERT INTO tableName (Student Roll Num, Student Name, StudentEmailID, 10th %, 12th %, Current  % ( or CGPA) , College Name, Department, Current Semester, WCF Mentor, WCF E-Mail ID, Batch, Stream, College Code, Stream Code, PBL_ID, Tr.No) VALUES ('21CS061', 'Naveen S', 'naveen2003sn@gmail.com', '68', '78', '7.5', 'Nandha Engineering College, Erode', 'CSE', 'VI', 'J.Radha', 'radha@nandhaengg.org', '2', 'JAVA Full Stack', '125', 'J', 'J_1250080', 'TNext_FY25_125_01_J');
INSERT INTO tableName (Student Roll Num, Student Name, StudentEmailID, 10th %, 12th %, Current  % ( or CGPA) , College Name, Department, Current Semester, WCF Mentor, WCF E-Mail ID, Batch, Stream, College Code, Stream Code, PBL_ID, Tr.No) VALUES ('21CS062', 'Naveena Devi S', 'srinivasans46782@gmail.com', '79.9', '89.1', '8.515', 'Nandha Engineering College, Erode', 'CSE', 'VI', 'J.Radha', 'radha@nandhaengg.org', '2', 'JAVA Full Stack', '125', 'J', 'J_1250081', 'TNext_FY25_125_01_J');
INSERT INTO tableName (Student Roll Num, Student Name, StudentEmailID, 10th %, 12th %, Current  % ( or CGPA) , College Name, Department, Current Semester, WCF Mentor, WCF E-Mail ID, Batch, Stream, College Code, Stream Code, PBL_ID, Tr.No) VALUES ('21CS065', 'Poornima', 'poornimadurairaj31@gmail.com', '83.4', '89', '8.3', 'Nandha Engineering College, Erode', 'CSE', 'VI', 'J.Radha', 'radha@nandhaengg.org', '2', 'JAVA Full Stack', '125', 'J', 'J_1250082', 'TNext_FY25_125_01_J');
INSERT INTO tableName (Student Roll Num, Student Name, StudentEmailID, 10th %, 12th %, Current  % ( or CGPA) , College Name, Department, Current Semester, WCF Mentor, WCF E-Mail ID, Batch, Stream, College Code, Stream Code, PBL_ID, Tr.No) VALUES ('21CS066', 'Poovarasu.K', 'poovarasuk2033@gmail.com', '83.6', '87.6', '7.5', 'Nandha Engineering College, Erode', 'CSE', 'VI', 'J.Radha', 'radha@nandhaengg.org', '2', 'JAVA Full Stack', '125', 'J', 'J_1250083', 'TNext_FY25_125_01_J');
INSERT INTO tableName (Student Roll Num, Student Name, StudentEmailID, 10th %, 12th %, Current  % ( or CGPA) , College Name, Department, Current Semester, WCF Mentor, WCF E-Mail ID, Batch, Stream, College Code, Stream Code, PBL_ID, Tr.No) VALUES ('21CS068', 'Pranav S', 'pranav.itsmee@gmail.com', '83', '88.57', '8.441', 'Nandha Engineering College, Erode', 'CSE', 'VI', 'J.Radha', 'radha@nandhaengg.org', '2', 'JAVA Full Stack', '125', 'J', 'J_1250084', 'TNext_FY25_125_01_J');
INSERT INTO tableName (Student Roll Num, Student Name, StudentEmailID, 10th %, 12th %, Current  % ( or CGPA) , College Name, Department, Current Semester, WCF Mentor, WCF E-Mail ID, Batch, Stream, College Code, Stream Code, PBL_ID, Tr.No) VALUES ('21CS069', 'Praveen. N', 'praveenpv149@gmail.com', '77.8', '82.05', '7.964', 'Nandha Engineering College, Erode', 'CSE', 'VI', 'J.Radha', 'radha@nandhaengg.org', '2', 'JAVA Full Stack', '125', 'J', 'J_1250085', 'TNext_FY25_125_01_J');
INSERT INTO tableName (Student Roll Num, Student Name, StudentEmailID, 10th %, 12th %, Current  % ( or CGPA) , College Name, Department, Current Semester, WCF Mentor, WCF E-Mail ID, Batch, Stream, College Code, Stream Code, PBL_ID, Tr.No) VALUES ('21CS070', 'Preetha R', 'preetharam230@gmail.com', '82.8', '88.67', '8.346', 'Nandha Engineering College, Erode', 'CSE', 'VI', 'J.Radha', 'radha@nandhaengg.org', '2', 'JAVA Full Stack', '125', 'J', 'J_1250086', 'TNext_FY25_125_01_J');
INSERT INTO tableName (Student Roll Num, Student Name, StudentEmailID, 10th %, 12th %, Current  % ( or CGPA) , College Name, Department, Current Semester, WCF Mentor, WCF E-Mail ID, Batch, Stream, College Code, Stream Code, PBL_ID, Tr.No) VALUES ('21CS026', 'R Gowri Shankar', 'gowrishankarkrj07@gmail.com', '88.8', '88.3', '7.8', 'Nandha Engineering College, Erode', 'CSE', 'VI', 'J.Radha', 'radha@nandhaengg.org', '2', 'JAVA Full Stack', '125', 'J', 'J_1250087', 'TNext_FY25_125_01_J');
INSERT INTO tableName (Student Roll Num, Student Name, StudentEmailID, 10th %, 12th %, Current  % ( or CGPA) , College Name, Department, Current Semester, WCF Mentor, WCF E-Mail ID, Batch, Stream, College Code, Stream Code, PBL_ID, Tr.No) VALUES ('21CS071', 'R V Rahuls Raja', 'rahulsraja65@gmail.com', '81', '81.88', '7.855', 'Nandha Engineering College, Erode', 'CSE', 'VI', 'J.Radha', 'radha@nandhaengg.org', '2', 'JAVA Full Stack', '125', 'J', 'J_1250088', 'TNext_FY25_125_01_J');
INSERT INTO tableName (Student Roll Num, Student Name, StudentEmailID, 10th %, 12th %, Current  % ( or CGPA) , College Name, Department, Current Semester, WCF Mentor, WCF E-Mail ID, Batch, Stream, College Code, Stream Code, PBL_ID, Tr.No) VALUES ('21CS072', 'Rajasekar J', 'rajasekartrigo@gmail.com', '79', '83', '7.5', 'Nandha Engineering College, Erode', 'CSE', 'VI', 'J.Radha', 'radha@nandhaengg.org', '2', 'JAVA Full Stack', '125', 'J', 'J_1250089', 'TNext_FY25_125_01_J');
INSERT INTO tableName (Student Roll Num, Student Name, StudentEmailID, 10th %, 12th %, Current  % ( or CGPA) , College Name, Department, Current Semester, WCF Mentor, WCF E-Mail ID, Batch, Stream, College Code, Stream Code, PBL_ID, Tr.No) VALUES ('21CS073', 'Rangaiyan S', 'rangaiyan29@gmail.com', '76.2', '83.41', '7.9', 'Nandha Engineering College, Erode', 'CSE', 'VI', 'J.Radha', 'radha@nandhaengg.org', '2', 'JAVA Full Stack', '125', 'J', 'J_1250090', 'TNext_FY25_125_01_J');
INSERT INTO tableName (Student Roll Num, Student Name, StudentEmailID, 10th %, 12th %, Current  % ( or CGPA) , College Name, Department, Current Semester, WCF Mentor, WCF E-Mail ID, Batch, Stream, College Code, Stream Code, PBL_ID, Tr.No) VALUES ('21CS059', 'S Naveen Kumar', 'naveen909595@gmail.com', '77.8', '83.33', '8.36', 'Nandha Engineering College, Erode', 'CSE', 'VI', 'J.Radha', 'radha@nandhaengg.org', '2', 'JAVA Full Stack', '125', 'J', 'J_1250091', 'TNext_FY25_125_01_J');
INSERT INTO tableName (Student Roll Num, Student Name, StudentEmailID, 10th %, 12th %, Current  % ( or CGPA) , College Name, Department, Current Semester, WCF Mentor, WCF E-Mail ID, Batch, Stream, College Code, Stream Code, PBL_ID, Tr.No) VALUES ('21CS074', 'Sakthivel M S', 'sakthivelms1405@gmail.com', '95.4', '93.6', '9.002', 'Nandha Engineering College, Erode', 'CSE', 'VI', 'J.Radha', 'radha@nandhaengg.org', '2', 'JAVA Full Stack', '125', 'J', 'J_1250092', 'TNext_FY25_125_01_J');
INSERT INTO tableName (Student Roll Num, Student Name, StudentEmailID, 10th %, 12th %, Current  % ( or CGPA) , College Name, Department, Current Semester, WCF Mentor, WCF E-Mail ID, Batch, Stream, College Code, Stream Code, PBL_ID, Tr.No) VALUES ('21CS077', 'Santhosh Kumar K', 'santhosh6384984762@gmail.com', '80.8', '82.5', '7.571', 'Nandha Engineering College, Erode', 'CSE', 'VI', 'J.Radha', 'radha@nandhaengg.org', '2', 'JAVA Full Stack', '125', 'J', 'J_1250093', 'TNext_FY25_125_01_J');
INSERT INTO tableName (Student Roll Num, Student Name, StudentEmailID, 10th %, 12th %, Current  % ( or CGPA) , College Name, Department, Current Semester, WCF Mentor, WCF E-Mail ID, Batch, Stream, College Code, Stream Code, PBL_ID, Tr.No) VALUES ('21CS078', 'Santhosh M', 'santhosh12232@gmail.com', '86.8', '89.66', '8.049', 'Nandha Engineering College, Erode', 'CSE', 'VI', 'J.Radha', 'radha@nandhaengg.org', '2', 'JAVA Full Stack', '125', 'J', 'J_1250094', 'TNext_FY25_125_01_J');
INSERT INTO tableName (Student Roll Num, Student Name, StudentEmailID, 10th %, 12th %, Current  % ( or CGPA) , College Name, Department, Current Semester, WCF Mentor, WCF E-Mail ID, Batch, Stream, College Code, Stream Code, PBL_ID, Tr.No) VALUES ('21CS079', 'Santhosh T K', 'santhoshmoorthi8903@gmail.com', '86.2', '89.423', '8.27', 'Nandha Engineering College, Erode', 'CSE', 'VI', 'J.Radha', 'radha@nandhaengg.org', '2', 'JAVA Full Stack', '125', 'J', 'J_1250095', 'TNext_FY25_125_01_J');
INSERT INTO tableName (Student Roll Num, Student Name, StudentEmailID, 10th %, 12th %, Current  % ( or CGPA) , College Name, Department, Current Semester, WCF Mentor, WCF E-Mail ID, Batch, Stream, College Code, Stream Code, PBL_ID, Tr.No) VALUES ('21CS080', 'Saravanana S', 'editorsarven@gmail.com', '78', '82.16', '7.5', 'Nandha Engineering College, Erode', 'CSE', 'VI', 'J.Radha', 'radha@nandhaengg.org', '2', 'JAVA Full Stack', '125', 'J', 'J_1250096', 'TNext_FY25_125_01_J');
INSERT INTO tableName (Student Roll Num, Student Name, StudentEmailID, 10th %, 12th %, Current  % ( or CGPA) , College Name, Department, Current Semester, WCF Mentor, WCF E-Mail ID, Batch, Stream, College Code, Stream Code, PBL_ID, Tr.No) VALUES ('21CS081', 'Sehshan Surya G', 'sehshansurya@gmail.com', '88.6', '87.69', '8.4435', 'Nandha Engineering College, Erode', 'CSE', 'VI', 'J.Radha', 'radha@nandhaengg.org', '2', 'JAVA Full Stack', '125', 'J', 'J_1250097', 'TNext_FY25_125_01_J');
INSERT INTO tableName (Student Roll Num, Student Name, StudentEmailID, 10th %, 12th %, Current  % ( or CGPA) , College Name, Department, Current Semester, WCF Mentor, WCF E-Mail ID, Batch, Stream, College Code, Stream Code, PBL_ID, Tr.No) VALUES ('21CS085', 'Sivashankar', 'sivashankarnkl@gmail.com', '80.8', '87.74', '7.5', 'Nandha Engineering College, Erode', 'CSE', 'VI', 'J.Radha', 'radha@nandhaengg.org', '2', 'JAVA Full Stack', '125', 'J', 'J_1250098', 'TNext_FY25_125_01_J');
INSERT INTO tableName (Student Roll Num, Student Name, StudentEmailID, 10th %, 12th %, Current  % ( or CGPA) , College Name, Department, Current Semester, WCF Mentor, WCF E-Mail ID, Batch, Stream, College Code, Stream Code, PBL_ID, Tr.No) VALUES ('21CS087', 'Soundarraj S', 'soundarraj3353@gmail.com', '78.4', '82.84', '7.56', 'Nandha Engineering College, Erode', 'CSE', 'VI', 'J.Radha', 'radha@nandhaengg.org', '2', 'JAVA Full Stack', '125', 'J', 'J_1250099', 'TNext_FY25_125_01_J');
INSERT INTO tableName (Student Roll Num, Student Name, StudentEmailID, 10th %, 12th %, Current  % ( or CGPA) , College Name, Department, Current Semester, WCF Mentor, WCF E-Mail ID, Batch, Stream, College Code, Stream Code, PBL_ID, Tr.No) VALUES ('21CS088', 'Sreesanth S', 'sree555santh@gmail.com', '76.6', '82.01', '7.982', 'Nandha Engineering College, Erode', 'CSE', 'VI', 'J.Radha', 'radha@nandhaengg.org', '2', 'JAVA Full Stack', '125', 'J', 'J_1250100', 'TNext_FY25_125_01_J');
INSERT INTO tableName (Student Roll Num, Student Name, StudentEmailID, 10th %, 12th %, Current  % ( or CGPA) , College Name, Department, Current Semester, WCF Mentor, WCF E-Mail ID, Batch, Stream, College Code, Stream Code, PBL_ID, Tr.No) VALUES ('21CS090', 'Sridhar B', 'sridharchml@gmail.com', '89.7', '90.6', '8.9', 'Nandha Engineering College, Erode', 'CSE', 'VI', 'J.Radha', 'radha@nandhaengg.org', '2', 'JAVA Full Stack', '125', 'J', 'J_1250101', 'TNext_FY25_125_01_J');
INSERT INTO tableName (Student Roll Num, Student Name, StudentEmailID, 10th %, 12th %, Current  % ( or CGPA) , College Name, Department, Current Semester, WCF Mentor, WCF E-Mail ID, Batch, Stream, College Code, Stream Code, PBL_ID, Tr.No) VALUES ('21CS089', 'Srihari S', 'srihariselvaraj7@gmail.com', '85.6', '87.75', '8.3', 'Nandha Engineering College, Erode', 'CSE', 'VI', 'J.Radha', 'radha@nandhaengg.org', '2', 'JAVA Full Stack', '125', 'J', 'J_1250102', 'TNext_FY25_125_01_J');
INSERT INTO tableName (Student Roll Num, Student Name, StudentEmailID, 10th %, 12th %, Current  % ( or CGPA) , College Name, Department, Current Semester, WCF Mentor, WCF E-Mail ID, Batch, Stream, College Code, Stream Code, PBL_ID, Tr.No) VALUES ('21CS091', 'Srihariraj R C', 'rcharichitra@gmail.com', '89.6', '90.5', '8.503', 'Nandha Engineering College, Erode', 'CSE', 'VI', 'J.Radha', 'radha@nandhaengg.org', '2', 'JAVA Full Stack', '125', 'J', 'J_1250103', 'TNext_FY25_125_01_J');
INSERT INTO tableName (Student Roll Num, Student Name, StudentEmailID, 10th %, 12th %, Current  % ( or CGPA) , College Name, Department, Current Semester, WCF Mentor, WCF E-Mail ID, Batch, Stream, College Code, Stream Code, PBL_ID, Tr.No) VALUES ('21CS092', 'Srikanth S', 'www.srikanth1212@gmail.com', '65', '74', '7.6', 'Nandha Engineering College, Erode', 'CSE', 'VI', 'J.Radha', 'radha@nandhaengg.org', '2', 'JAVA Full Stack', '125', 'J', 'J_1250104', 'TNext_FY25_125_01_J');
INSERT INTO tableName (Student Roll Num, Student Name, StudentEmailID, 10th %, 12th %, Current  % ( or CGPA) , College Name, Department, Current Semester, WCF Mentor, WCF E-Mail ID, Batch, Stream, College Code, Stream Code, PBL_ID, Tr.No) VALUES ('21CS093', 'Stanley.S', 'stanleysamped@gmail.com', '71', '81', '7.2', 'Nandha Engineering College, Erode', 'CSE', 'VI', 'J.Radha', 'radha@nandhaengg.org', '2', 'JAVA Full Stack', '125', 'J', 'J_1250105', 'TNext_FY25_125_01_J');
INSERT INTO tableName (Student Roll Num, Student Name, StudentEmailID, 10th %, 12th %, Current  % ( or CGPA) , College Name, Department, Current Semester, WCF Mentor, WCF E-Mail ID, Batch, Stream, College Code, Stream Code, PBL_ID, Tr.No) VALUES ('21CS094', 'Subika K V', 'subikakv@gmail.com', '84.2', '92', '8.62', 'Nandha Engineering College, Erode', 'CSE', 'VI', 'J.Radha', 'radha@nandhaengg.org', '2', 'JAVA Full Stack', '125', 'J', 'J_1250106', 'TNext_FY25_125_01_J');
INSERT INTO tableName (Student Roll Num, Student Name, StudentEmailID, 10th %, 12th %, Current  % ( or CGPA) , College Name, Department, Current Semester, WCF Mentor, WCF E-Mail ID, Batch, Stream, College Code, Stream Code, PBL_ID, Tr.No) VALUES ('21CS097', 'Surya Prakash V', 'vvms227@gmail.com', '80', '86', '7.9', 'Nandha Engineering College, Erode', 'CSE', 'VI', 'J.Radha', 'radha@nandhaengg.org', '2', 'JAVA Full Stack', '125', 'J', 'J_1250107', 'TNext_FY25_125_01_J');
INSERT INTO tableName (Student Roll Num, Student Name, StudentEmailID, 10th %, 12th %, Current  % ( or CGPA) , College Name, Department, Current Semester, WCF Mentor, WCF E-Mail ID, Batch, Stream, College Code, Stream Code, PBL_ID, Tr.No) VALUES ('21CS098', 'Surya S', 'gowthamsurya211@gmail.com', '68.4', '78.66', '7.47', 'Nandha Engineering College, Erode', 'CSE', 'VI', 'J.Radha', 'radha@nandhaengg.org', '2', 'JAVA Full Stack', '125', 'J', 'J_1250108', 'TNext_FY25_125_01_J');
INSERT INTO tableName (Student Roll Num, Student Name, StudentEmailID, 10th %, 12th %, Current  % ( or CGPA) , College Name, Department, Current Semester, WCF Mentor, WCF E-Mail ID, Batch, Stream, College Code, Stream Code, PBL_ID, Tr.No) VALUES ('21CS099', 'Sutharson Ma', 'sutharson.in@gmail.com', '75.8', '79.5', '8.1', 'Nandha Engineering College, Erode', 'CSE', 'VI', 'J.Radha', 'radha@nandhaengg.org', '2', 'JAVA Full Stack', '125', 'J', 'J_1250109', 'TNext_FY25_125_01_J');
INSERT INTO tableName (Student Roll Num, Student Name, StudentEmailID, 10th %, 12th %, Current  % ( or CGPA) , College Name, Department, Current Semester, WCF Mentor, WCF E-Mail ID, Batch, Stream, College Code, Stream Code, PBL_ID, Tr.No) VALUES ('21CS102', 'Tharun.L', 'tharunsadhur6609@gmail.com', '67.8', '78.47', '7.5', 'Nandha Engineering College, Erode', 'CSE', 'VI', 'J.Radha', 'radha@nandhaengg.org', '2', 'JAVA Full Stack', '125', 'J', 'J_1250110', 'TNext_FY25_125_01_J');
INSERT INTO tableName (Student Roll Num, Student Name, StudentEmailID, 10th %, 12th %, Current  % ( or CGPA) , College Name, Department, Current Semester, WCF Mentor, WCF E-Mail ID, Batch, Stream, College Code, Stream Code, PBL_ID, Tr.No) VALUES ('21CS104', 'Thirukkumaran S', 'thirusaraswathishanmugam@gmail.com', '90.5', '90.5', '8.215', 'Nandha Engineering College, Erode', 'CSE', 'VI', 'J.Radha', 'radha@nandhaengg.org', '2', 'JAVA Full Stack', '125', 'J', 'J_1250111', 'TNext_FY25_125_01_J');
INSERT INTO tableName (Student Roll Num, Student Name, StudentEmailID, 10th %, 12th %, Current  % ( or CGPA) , College Name, Department, Current Semester, WCF Mentor, WCF E-Mail ID, Batch, Stream, College Code, Stream Code, PBL_ID, Tr.No) VALUES ('21CS105', 'Thiviyaprakash E', 'thiviyaprakash11@gmail.com', '82.2', '86.75', '8.775', 'Nandha Engineering College, Erode', 'CSE', 'VI', 'J.Radha', 'radha@nandhaengg.org', '2', 'JAVA Full Stack', '125', 'J', 'J_1250112', 'TNext_FY25_125_01_J');
INSERT INTO tableName (Student Roll Num, Student Name, StudentEmailID, 10th %, 12th %, Current  % ( or CGPA) , College Name, Department, Current Semester, WCF Mentor, WCF E-Mail ID, Batch, Stream, College Code, Stream Code, PBL_ID, Tr.No) VALUES ('21CS108', 'Vasanth P', 'vasanthvibin1812@gmail.com', '94.2', '91.7', '8.9', 'Nandha Engineering College, Erode', 'CSE', 'VI', 'J.Radha', 'radha@nandhaengg.org', '2', 'JAVA Full Stack', '125', 'J', 'J_1250113', 'TNext_FY25_125_01_J');
INSERT INTO tableName (Student Roll Num, Student Name, StudentEmailID, 10th %, 12th %, Current  % ( or CGPA) , College Name, Department, Current Semester, WCF Mentor, WCF E-Mail ID, Batch, Stream, College Code, Stream Code, PBL_ID, Tr.No) VALUES ('21CS107', 'Vasanth R', 'vasanthramesh2277@gmail.com', '60', '75', '7.9', 'Nandha Engineering College, Erode', 'CSE', 'VI', 'J.Radha', 'radha@nandhaengg.org', '2', 'JAVA Full Stack', '125', 'J', 'J_1250114', 'TNext_FY25_125_01_J');
INSERT INTO tableName (Student Roll Num, Student Name, StudentEmailID, 10th %, 12th %, Current  % ( or CGPA) , College Name, Department, Current Semester, WCF Mentor, WCF E-Mail ID, Batch, Stream, College Code, Stream Code, PBL_ID, Tr.No) VALUES ('21CS110', 'Vignesh K', 'vigneshkumarasamy77@gmail.com', '82.4', '87.13', '8.328', 'Nandha Engineering College, Erode', 'CSE', 'VI', 'J.Radha', 'radha@nandhaengg.org', '2', 'JAVA Full Stack', '125', 'J', 'J_1250115', 'TNext_FY25_125_01_J');
INSERT INTO tableName (Student Roll Num, Student Name, StudentEmailID, 10th %, 12th %, Current  % ( or CGPA) , College Name, Department, Current Semester, WCF Mentor, WCF E-Mail ID, Batch, Stream, College Code, Stream Code, PBL_ID, Tr.No) VALUES ('21CS111', 'Vignesh V', 'vigneshvijay2704@gmail.com', '73', '79', '7.6', 'Nandha Engineering College, Erode', 'CSE', 'VI', 'J.Radha', 'radha@nandhaengg.org', '2', 'JAVA Full Stack', '125', 'J', 'J_1250116', 'TNext_FY25_125_01_J');
INSERT INTO tableName (Student Roll Num, Student Name, StudentEmailID, 10th %, 12th %, Current  % ( or CGPA) , College Name, Department, Current Semester, WCF Mentor, WCF E-Mail ID, Batch, Stream, College Code, Stream Code, PBL_ID, Tr.No) VALUES ('21CS112', 'Vijayasankar.T', 'vijayasankar0002@gmail.com', '79', '85.13', '7.8', 'Nandha Engineering College, Erode', 'CSE', 'VI', 'J.Radha', 'radha@nandhaengg.org', '2', 'JAVA Full Stack', '125', 'J', 'J_1250117', 'TNext_FY25_125_01_J');
INSERT INTO tableName (Student Roll Num, Student Name, StudentEmailID, 10th %, 12th %, Current  % ( or CGPA) , College Name, Department, Current Semester, WCF Mentor, WCF E-Mail ID, Batch, Stream, College Code, Stream Code, PBL_ID, Tr.No) VALUES ('21CS115', 'Vinitha.M', 'vinitha17062004m@gmail.com', '85.4', '88.83', '8.3', 'Nandha Engineering College, Erode', 'CSE', 'VI', 'J.Radha', 'radha@nandhaengg.org', '2', 'JAVA Full Stack', '125', 'J', 'J_1250118', 'TNext_FY25_125_01_J');
INSERT INTO tableName (Student Roll Num, Student Name, StudentEmailID, 10th %, 12th %, Current  % ( or CGPA) , College Name, Department, Current Semester, WCF Mentor, WCF E-Mail ID, Batch, Stream, College Code, Stream Code, PBL_ID, Tr.No) VALUES ('21CS116', 'Vinoda V R', 'vinorevathi2004@gmail.com', '87', '89.5', '8.3', 'Nandha Engineering College, Erode', 'CSE', 'VI', 'J.Radha', 'radha@nandhaengg.org', '2', 'JAVA Full Stack', '125', 'J', 'J_1250119', 'TNext_FY25_125_01_J');
INSERT INTO tableName (Student Roll Num, Student Name, StudentEmailID, 10th %, 12th %, Current  % ( or CGPA) , College Name, Department, Current Semester, WCF Mentor, WCF E-Mail ID, Batch, Stream, College Code, Stream Code, PBL_ID, Tr.No) VALUES ('21CS118', 'Vinoth R', 'raja2212rs@gmail.com', '91', '89.75', '7.8', 'Nandha Engineering College, Erode', 'CSE', 'VI', 'J.Radha', 'radha@nandhaengg.org', '2', 'JAVA Full Stack', '125', 'J', 'J_1250120', 'TNext_FY25_125_01_J');
INSERT INTO tableName (Student Roll Num, Student Name, StudentEmailID, 10th %, 12th %, Current  % ( or CGPA) , College Name, Department, Current Semester, WCF Mentor, WCF E-Mail ID, Batch, Stream, College Code, Stream Code, PBL_ID, Tr.No) VALUES ('21CS120', 'Yuvarani M', 'yuvaranimurugesh7@gmail.com', '84.4', '90.67', '8.72', 'Nandha Engineering College, Erode', 'CSE', 'VI', 'J.Radha', 'radha@nandhaengg.org', '2', 'JAVA Full Stack', '125', 'J', 'J_1250121', 'TNext_FY25_125_01_J');
INSERT INTO tableName (Student Roll Num, Student Name, StudentEmailID, 10th %, 12th %, Current  % ( or CGPA) , College Name, Department, Current Semester, WCF Mentor, WCF E-Mail ID, Batch, Stream, College Code, Stream Code, PBL_ID, Tr.No) VALUES ('21IT002', 'Amegadhanu.A', 'amegadhanu@gmail.com', '75', '78', '7', 'Nandha Engineering College, Erode', 'IT', 'VI', 'A.Bharathi', 'bharathi.a@nandhaengg.org', 'Batch 1', 'JAVA Full Stack', '125', 'J', 'J_1250122', 'TNext_FY25_125_01_J');
INSERT INTO tableName (Student Roll Num, Student Name, StudentEmailID, 10th %, 12th %, Current  % ( or CGPA) , College Name, Department, Current Semester, WCF Mentor, WCF E-Mail ID, Batch, Stream, College Code, Stream Code, PBL_ID, Tr.No) VALUES ('21IT005', 'Aswin', 'aswinveera2k4@gmail.com', '77', '84', '8.1', 'Nandha Engineering College, Erode', 'IT', 'VI', 'A.Bharathi', 'bharathi.a@nandhaengg.org', 'Batch 1', 'JAVA Full Stack', '125', 'J', 'J_1250123', 'TNext_FY25_125_01_J');
INSERT INTO tableName (Student Roll Num, Student Name, StudentEmailID, 10th %, 12th %, Current  % ( or CGPA) , College Name, Department, Current Semester, WCF Mentor, WCF E-Mail ID, Batch, Stream, College Code, Stream Code, PBL_ID, Tr.No) VALUES ('21ITL01', 'Barani I', 'baranibarani317@gmail.com', '75.8', '89', '7.95', 'Nandha Engineering College, Erode', 'IT', 'VI', 'A.Bharathi', 'bharathi.a@nandhaengg.org', 'Batch 1', 'JAVA Full Stack', '125', 'J', 'J_1250124', 'TNext_FY25_125_01_J');
INSERT INTO tableName (Student Roll Num, Student Name, StudentEmailID, 10th %, 12th %, Current  % ( or CGPA) , College Name, Department, Current Semester, WCF Mentor, WCF E-Mail ID, Batch, Stream, College Code, Stream Code, PBL_ID, Tr.No) VALUES ('21IT008', 'Bharath M', 'bharathalpha001@gmail.com', '81', '81.5', '7.9', 'Nandha Engineering College, Erode', 'IT', 'VI', 'A.Bharathi', 'bharathi.a@nandhaengg.org', 'Batch 1', 'JAVA Full Stack', '125', 'J', 'J_1250125', 'TNext_FY25_125_01_J');
INSERT INTO tableName (Student Roll Num, Student Name, StudentEmailID, 10th %, 12th %, Current  % ( or CGPA) , College Name, Department, Current Semester, WCF Mentor, WCF E-Mail ID, Batch, Stream, College Code, Stream Code, PBL_ID, Tr.No) VALUES ('21IT009', 'Chandru B', 'chandrurolexsir12@gmail.com', '71.8', '83.3', '7.5', 'Nandha Engineering College, Erode', 'IT', 'VI', 'A.Bharathi', 'bharathi.a@nandhaengg.org', 'Batch 1', 'JAVA Full Stack', '125', 'J', 'J_1250126', 'TNext_FY25_125_01_J');
INSERT INTO tableName (Student Roll Num, Student Name, StudentEmailID, 10th %, 12th %, Current  % ( or CGPA) , College Name, Department, Current Semester, WCF Mentor, WCF E-Mail ID, Batch, Stream, College Code, Stream Code, PBL_ID, Tr.No) VALUES ('21IT010', 'Deepa C', 'deepac2004@gmail.com', '81.8', '85.3', '8.5', 'Nandha Engineering College, Erode', 'IT', 'VI', 'A.Bharathi', 'bharathi.a@nandhaengg.org', 'Batch 1', 'JAVA Full Stack', '125', 'J', 'J_1250127', 'TNext_FY25_125_01_J');
INSERT INTO tableName (Student Roll Num, Student Name, StudentEmailID, 10th %, 12th %, Current  % ( or CGPA) , College Name, Department, Current Semester, WCF Mentor, WCF E-Mail ID, Batch, Stream, College Code, Stream Code, PBL_ID, Tr.No) VALUES ('21ITL02', 'Dhanush Ms', 'dhanushms9665@gmail.com', '82.8', '90', '8.2', 'Nandha Engineering College, Erode', 'IT', 'VI', 'A.Bharathi', 'bharathi.a@nandhaengg.org', 'Batch 1', 'JAVA Full Stack', '125', 'J', 'J_1250128', 'TNext_FY25_125_01_J');
INSERT INTO tableName (Student Roll Num, Student Name, StudentEmailID, 10th %, 12th %, Current  % ( or CGPA) , College Name, Department, Current Semester, WCF Mentor, WCF E-Mail ID, Batch, Stream, College Code, Stream Code, PBL_ID, Tr.No) VALUES ('21IT014', 'Dhanushya K', 'kumardhanushya51@gmail.com', '80', '86', '9.3', 'Nandha Engineering College, Erode', 'IT', 'VI', 'A.Bharathi', 'bharathi.a@nandhaengg.org', 'Batch 1', 'JAVA Full Stack', '125', 'J', 'J_1250129', 'TNext_FY25_125_01_J');
INSERT INTO tableName (Student Roll Num, Student Name, StudentEmailID, 10th %, 12th %, Current  % ( or CGPA) , College Name, Department, Current Semester, WCF Mentor, WCF E-Mail ID, Batch, Stream, College Code, Stream Code, PBL_ID, Tr.No) VALUES ('21IT013', 'Dhanusree R', 'sarangetamil22@gmail.com', '90.2', '92', '80.5', 'Nandha Engineering College, Erode', 'IT', 'VI', 'A.Bharathi', 'bharathi.a@nandhaengg.org', 'Batch 1', 'JAVA Full Stack', '125', 'J', 'J_1250130', 'TNext_FY25_125_01_J');
INSERT INTO tableName (Student Roll Num, Student Name, StudentEmailID, 10th %, 12th %, Current  % ( or CGPA) , College Name, Department, Current Semester, WCF Mentor, WCF E-Mail ID, Batch, Stream, College Code, Stream Code, PBL_ID, Tr.No) VALUES ('21IT019', 'Gowarthine M S', 'gowarthinemurugan@gmail.com', '93.8', '90.8', '8.5', 'Nandha Engineering College, Erode', 'IT', 'VI', 'A.Bharathi', 'bharathi.a@nandhaengg.org', 'Batch 1', 'JAVA Full Stack', '125', 'J', 'J_1250131', 'TNext_FY25_125_01_J');
INSERT INTO tableName (Student Roll Num, Student Name, StudentEmailID, 10th %, 12th %, Current  % ( or CGPA) , College Name, Department, Current Semester, WCF Mentor, WCF E-Mail ID, Batch, Stream, College Code, Stream Code, PBL_ID, Tr.No) VALUES ('21IT020', 'Harish D', 'onlyme2420@gmail.com', '75', '84', '7.8', 'Nandha Engineering College, Erode', 'IT', 'VI', 'A.Bharathi', 'bharathi.a@nandhaengg.org', 'Batch 1', 'JAVA Full Stack', '125', 'J', 'J_1250132', 'TNext_FY25_125_01_J');
INSERT INTO tableName (Student Roll Num, Student Name, StudentEmailID, 10th %, 12th %, Current  % ( or CGPA) , College Name, Department, Current Semester, WCF Mentor, WCF E-Mail ID, Batch, Stream, College Code, Stream Code, PBL_ID, Tr.No) VALUES ('21IT021', 'Harshavardhini M', 'harsharenu03@gmail.com', '92', '91.8', '9.2', 'Nandha Engineering College, Erode', 'IT', 'VI', 'A.Bharathi', 'bharathi.a@nandhaengg.org', 'Batch 1', 'JAVA Full Stack', '125', 'J', 'J_1250133', 'TNext_FY25_125_01_J');
INSERT INTO tableName (Student Roll Num, Student Name, StudentEmailID, 10th %, 12th %, Current  % ( or CGPA) , College Name, Department, Current Semester, WCF Mentor, WCF E-Mail ID, Batch, Stream, College Code, Stream Code, PBL_ID, Tr.No) VALUES ('21IT022', 'Hemanth C', 'hemanthcv2003@gmail.com', '84', '88.5', '7.3', 'Nandha Engineering College, Erode', 'IT', 'VI', 'A.Bharathi', 'bharathi.a@nandhaengg.org', 'Batch 1', 'JAVA Full Stack', '125', 'J', 'J_1250134', 'TNext_FY25_125_01_J');
INSERT INTO tableName (Student Roll Num, Student Name, StudentEmailID, 10th %, 12th %, Current  % ( or CGPA) , College Name, Department, Current Semester, WCF Mentor, WCF E-Mail ID, Batch, Stream, College Code, Stream Code, PBL_ID, Tr.No) VALUES ('21IT023', 'Janani Priya S', 'jananipriya182004@gmail.com', '91.6', '92.8', '9', 'Nandha Engineering College, Erode', 'IT', 'VI', 'A.Bharathi', 'bharathi.a@nandhaengg.org', 'Batch 1', 'JAVA Full Stack', '125', 'J', 'J_1250135', 'TNext_FY25_125_01_J');
INSERT INTO tableName (Student Roll Num, Student Name, StudentEmailID, 10th %, 12th %, Current  % ( or CGPA) , College Name, Department, Current Semester, WCF Mentor, WCF E-Mail ID, Batch, Stream, College Code, Stream Code, PBL_ID, Tr.No) VALUES ('21IT026', 'Kumuthavalli .V', 'kumuthavalliaasha@gmail.com', '81', '84', '8.3', 'Nandha Engineering College, Erode', 'IT', 'VI', 'A.Bharathi', 'bharathi.a@nandhaengg.org', 'Batch 1', 'JAVA Full Stack', '125', 'J', 'J_1250136', 'TNext_FY25_125_01_J');
INSERT INTO tableName (Student Roll Num, Student Name, StudentEmailID, 10th %, 12th %, Current  % ( or CGPA) , College Name, Department, Current Semester, WCF Mentor, WCF E-Mail ID, Batch, Stream, College Code, Stream Code, PBL_ID, Tr.No) VALUES ('21IT028', 'Logesh T', 'logesht2003@gmail.com', '85', '88.8', '8.5', 'Nandha Engineering College, Erode', 'IT', 'VI', 'A.Bharathi', 'bharathi.a@nandhaengg.org', 'Batch 1', 'JAVA Full Stack', '125', 'J', 'J_1250137', 'TNext_FY25_125_01_J');
INSERT INTO tableName (Student Roll Num, Student Name, StudentEmailID, 10th %, 12th %, Current  % ( or CGPA) , College Name, Department, Current Semester, WCF Mentor, WCF E-Mail ID, Batch, Stream, College Code, Stream Code, PBL_ID, Tr.No) VALUES ('21IT007', 'M Barkath Ali', 'naughtyjavith@gmail.com', '64', '75.5', '8.2', 'Nandha Engineering College, Erode', 'IT', 'VI', 'A.Bharathi', 'bharathi.a@nandhaengg.org', 'Batch 1', 'JAVA Full Stack', '125', 'J', 'J_1250138', 'TNext_FY25_125_01_J');
INSERT INTO tableName (Student Roll Num, Student Name, StudentEmailID, 10th %, 12th %, Current  % ( or CGPA) , College Name, Department, Current Semester, WCF Mentor, WCF E-Mail ID, Batch, Stream, College Code, Stream Code, PBL_ID, Tr.No) VALUES ('21IT012', 'M. Deepika', 'deepideepika00629@gmail.com', '82.8', '88.5', '7.4', 'Nandha Engineering College, Erode', 'IT', 'VI', 'A.Bharathi', 'bharathi.a@nandhaengg.org', 'Batch 1', 'JAVA Full Stack', '125', 'J', 'J_1250139', 'TNext_FY25_125_01_J');
INSERT INTO tableName (Student Roll Num, Student Name, StudentEmailID, 10th %, 12th %, Current  % ( or CGPA) , College Name, Department, Current Semester, WCF Mentor, WCF E-Mail ID, Batch, Stream, College Code, Stream Code, PBL_ID, Tr.No) VALUES ('21IT004', 'M.P.Ashok', 'aashok03609@gmail.com', '67', '76', '8', 'Nandha Engineering College, Erode', 'IT', 'VI', 'A.Bharathi', 'bharathi.a@nandhaengg.org', 'Batch 1', 'JAVA Full Stack', '125', 'J', 'J_1250140', 'TNext_FY25_125_01_J');
INSERT INTO tableName (Student Roll Num, Student Name, StudentEmailID, 10th %, 12th %, Current  % ( or CGPA) , College Name, Department, Current Semester, WCF Mentor, WCF E-Mail ID, Batch, Stream, College Code, Stream Code, PBL_ID, Tr.No) VALUES ('21IT029', 'Maheswari.S.K', 'maheswarikrish20@gmail.com', '80.4', '86', '8.3', 'Nandha Engineering College, Erode', 'IT', 'VI', 'A.Bharathi', 'bharathi.a@nandhaengg.org', 'Batch 1', 'JAVA Full Stack', '125', 'J', 'J_1250141', 'TNext_FY25_125_01_J');
INSERT INTO tableName (Student Roll Num, Student Name, StudentEmailID, 10th %, 12th %, Current  % ( or CGPA) , College Name, Department, Current Semester, WCF Mentor, WCF E-Mail ID, Batch, Stream, College Code, Stream Code, PBL_ID, Tr.No) VALUES ('21IT031', 'Mathan M', 'mathan44862@gmail.com', '73', '83.5', '8.7', 'Nandha Engineering College, Erode', 'IT', 'VI', 'A.Bharathi', 'bharathi.a@nandhaengg.org', 'Batch 1', 'JAVA Full Stack', '125', 'J', 'J_1250142', 'TNext_FY25_125_01_J');
INSERT INTO tableName (Student Roll Num, Student Name, StudentEmailID, 10th %, 12th %, Current  % ( or CGPA) , College Name, Department, Current Semester, WCF Mentor, WCF E-Mail ID, Batch, Stream, College Code, Stream Code, PBL_ID, Tr.No) VALUES ('21IT032', 'Moulitharan S', 'moulitharan2020@gmail.com', '65.2', '78', '7.2', 'Nandha Engineering College, Erode', 'IT', 'VI', 'A.Bharathi', 'bharathi.a@nandhaengg.org', 'Batch 1', 'JAVA Full Stack', '125', 'J', 'J_1250143', 'TNext_FY25_125_01_J');
INSERT INTO tableName (Student Roll Num, Student Name, StudentEmailID, 10th %, 12th %, Current  % ( or CGPA) , College Name, Department, Current Semester, WCF Mentor, WCF E-Mail ID, Batch, Stream, College Code, Stream Code, PBL_ID, Tr.No) VALUES ('21IT034', 'Poorani R', 'pooraniramesh027@gmail.com', '87', '84', '8.5', 'Nandha Engineering College, Erode', 'IT', 'VI', 'A.Bharathi', 'bharathi.a@nandhaengg.org', 'Batch 1', 'JAVA Full Stack', '125', 'J', 'J_1250144', 'TNext_FY25_125_01_J');
INSERT INTO tableName (Student Roll Num, Student Name, StudentEmailID, 10th %, 12th %, Current  % ( or CGPA) , College Name, Department, Current Semester, WCF Mentor, WCF E-Mail ID, Batch, Stream, College Code, Stream Code, PBL_ID, Tr.No) VALUES ('21ITL06', 'Premkumar C', 'cpremkumar2000@gmail.com', '94', '87', '8', 'Nandha Engineering College, Erode', 'IT', 'VI', 'A.Bharathi', 'bharathi.a@nandhaengg.org', 'Batch 1', 'JAVA Full Stack', '125', 'J', 'J_1250145', 'TNext_FY25_125_01_J');
INSERT INTO tableName (Student Roll Num, Student Name, StudentEmailID, 10th %, 12th %, Current  % ( or CGPA) , College Name, Department, Current Semester, WCF Mentor, WCF E-Mail ID, Batch, Stream, College Code, Stream Code, PBL_ID, Tr.No) VALUES ('21IT035', 'Priyashanmugam A', 'a.priyashanmugam2004@gmail.com', '83', '88', '7.5', 'Nandha Engineering College, Erode', 'IT', 'VI', 'A.Bharathi', 'bharathi.a@nandhaengg.org', 'Batch 1', 'JAVA Full Stack', '125', 'J', 'J_1250146', 'TNext_FY25_125_01_J');
INSERT INTO tableName (Student Roll Num, Student Name, StudentEmailID, 10th %, 12th %, Current  % ( or CGPA) , College Name, Department, Current Semester, WCF Mentor, WCF E-Mail ID, Batch, Stream, College Code, Stream Code, PBL_ID, Tr.No) VALUES ('21IT039', 'Ritika G', 'rithi1842@gmail.com', '95.2', '65.83', '8.9', 'Nandha Engineering College, Erode', 'IT', 'VI', 'A.Bharathi', 'bharathi.a@nandhaengg.org', 'Batch 1', 'JAVA Full Stack', '125', 'J', 'J_1250147', 'TNext_FY25_125_01_J');
INSERT INTO tableName (Student Roll Num, Student Name, StudentEmailID, 10th %, 12th %, Current  % ( or CGPA) , College Name, Department, Current Semester, WCF Mentor, WCF E-Mail ID, Batch, Stream, College Code, Stream Code, PBL_ID, Tr.No) VALUES ('21IT040', 'Sai Balaji G', 'saibalajijaya786@gmail.com', '84.2', '86.7', '7.5', 'Nandha Engineering College, Erode', 'IT', 'VI', 'A.Bharathi', 'bharathi.a@nandhaengg.org', 'Batch 1', 'JAVA Full Stack', '125', 'J', 'J_1250148', 'TNext_FY25_125_01_J');
INSERT INTO tableName (Student Roll Num, Student Name, StudentEmailID, 10th %, 12th %, Current  % ( or CGPA) , College Name, Department, Current Semester, WCF Mentor, WCF E-Mail ID, Batch, Stream, College Code, Stream Code, PBL_ID, Tr.No) VALUES ('21IT042', 'Sanjay R', 'sanjayrajasmart@gmail.com', '88.4', '90.6', '8.25', 'Nandha Engineering College, Erode', 'IT', 'VI', 'A.Bharathi', 'bharathi.a@nandhaengg.org', 'Batch 1', 'JAVA Full Stack', '125', 'J', 'J_1250149', 'TNext_FY25_125_01_J');
INSERT INTO tableName (Student Roll Num, Student Name, StudentEmailID, 10th %, 12th %, Current  % ( or CGPA) , College Name, Department, Current Semester, WCF Mentor, WCF E-Mail ID, Batch, Stream, College Code, Stream Code, PBL_ID, Tr.No) VALUES ('21IT043', 'Sanjay R', 'rsanjayravi2004@gmail.com', '78', '86', '8', 'Nandha Engineering College, Erode', 'IT', 'VI', 'A.Bharathi', 'bharathi.a@nandhaengg.org', 'Batch 1', 'JAVA Full Stack', '125', 'J', 'J_1250150', 'TNext_FY25_125_01_J');
INSERT INTO tableName (Student Roll Num, Student Name, StudentEmailID, 10th %, 12th %, Current  % ( or CGPA) , College Name, Department, Current Semester, WCF Mentor, WCF E-Mail ID, Batch, Stream, College Code, Stream Code, PBL_ID, Tr.No) VALUES ('21IT046', 'Sathyan S', 'sathyasivakumar315@gmail.com', '84.6', '84.6', '7.5', 'Nandha Engineering College, Erode', 'IT', 'VI', 'A.Bharathi', 'bharathi.a@nandhaengg.org', 'Batch 1', 'JAVA Full Stack', '125', 'J', 'J_1250151', 'TNext_FY25_125_01_J');
INSERT INTO tableName (Student Roll Num, Student Name, StudentEmailID, 10th %, 12th %, Current  % ( or CGPA) , College Name, Department, Current Semester, WCF Mentor, WCF E-Mail ID, Batch, Stream, College Code, Stream Code, PBL_ID, Tr.No) VALUES ('21IT049', 'Suganya C', 'chiyaansugan84@gmail.com', '84.4', '87.3', '8.6', 'Nandha Engineering College, Erode', 'IT', 'VI', 'A.Bharathi', 'bharathi.a@nandhaengg.org', 'Batch 1', 'JAVA Full Stack', '125', 'J', 'J_1250152', 'TNext_FY25_125_01_J');
INSERT INTO tableName (Student Roll Num, Student Name, StudentEmailID, 10th %, 12th %, Current  % ( or CGPA) , College Name, Department, Current Semester, WCF Mentor, WCF E-Mail ID, Batch, Stream, College Code, Stream Code, PBL_ID, Tr.No) VALUES ('21IT050', 'Suraj R', 'surajvishwakarma51328@gmail.com', '89', '89.7', '7.7', 'Nandha Engineering College, Erode', 'IT', 'VI', 'A.Bharathi', 'bharathi.a@nandhaengg.org', 'Batch 1', 'JAVA Full Stack', '125', 'J', 'J_1250153', 'TNext_FY25_125_01_J');
INSERT INTO tableName (Student Roll Num, Student Name, StudentEmailID, 10th %, 12th %, Current  % ( or CGPA) , College Name, Department, Current Semester, WCF Mentor, WCF E-Mail ID, Batch, Stream, College Code, Stream Code, PBL_ID, Tr.No) VALUES ('21IT051', 'Thangavarathan G', 'ramprakashg4@gmail.com', '80.01', '85.85', '7.5', 'Nandha Engineering College, Erode', 'IT', 'VI', 'A.Bharathi', 'bharathi.a@nandhaengg.org', 'Batch 1', 'JAVA Full Stack', '125', 'J', 'J_1250154', 'TNext_FY25_125_01_J');
INSERT INTO tableName (Student Roll Num, Student Name, StudentEmailID, 10th %, 12th %, Current  % ( or CGPA) , College Name, Department, Current Semester, WCF Mentor, WCF E-Mail ID, Batch, Stream, College Code, Stream Code, PBL_ID, Tr.No) VALUES ('21IT052', 'Thirumeni M', 'thirumeni948@gmail.com', '89', '91.25', '8.5', 'Nandha Engineering College, Erode', 'IT', 'VI', 'A.Bharathi', 'bharathi.a@nandhaengg.org', 'Batch 1', 'JAVA Full Stack', '125', 'J', 'J_1250155', 'TNext_FY25_125_01_J');
INSERT INTO tableName (Student Roll Num, Student Name, StudentEmailID, 10th %, 12th %, Current  % ( or CGPA) , College Name, Department, Current Semester, WCF Mentor, WCF E-Mail ID, Batch, Stream, College Code, Stream Code, PBL_ID, Tr.No) VALUES ('21IT053', 'Varsha A', 'varshaalagar2003@gmail.com', '90.6', '92.4', '8.98', 'Nandha Engineering College, Erode', 'IT', 'VI', 'A.Bharathi', 'bharathi.a@nandhaengg.org', 'Batch 1', 'JAVA Full Stack', '125', 'J', 'J_1250156', 'TNext_FY25_125_01_J');
INSERT INTO tableName (Student Roll Num, Student Name, StudentEmailID, 10th %, 12th %, Current  % ( or CGPA) , College Name, Department, Current Semester, WCF Mentor, WCF E-Mail ID, Batch, Stream, College Code, Stream Code, PBL_ID, Tr.No) VALUES ('21IT054', 'Varshaa.B', 'varshaa2242004@gmail.com', '79', '84.48', '8.732', 'Nandha Engineering College, Erode', 'IT', 'VI', 'A.Bharathi', 'bharathi.a@nandhaengg.org', 'Batch 1', 'JAVA Full Stack', '125', 'J', 'J_1250157', 'TNext_FY25_125_01_J');
INSERT INTO tableName (Student Roll Num, Student Name, StudentEmailID, 10th %, 12th %, Current  % ( or CGPA) , College Name, Department, Current Semester, WCF Mentor, WCF E-Mail ID, Batch, Stream, College Code, Stream Code, PBL_ID, Tr.No) VALUES ('21IT057', 'Vignesh R', 'vigneshppa@gmail.com', '85.4', '89.8', '8.3', 'Nandha Engineering College, Erode', 'IT', 'VI', 'A.Bharathi', 'bharathi.a@nandhaengg.org', 'Batch 1', 'JAVA Full Stack', '125', 'J', 'J_1250158', 'TNext_FY25_125_01_J');
INSERT INTO tableName (Student Roll Num, Student Name, StudentEmailID, 10th %, 12th %, Current  % ( or CGPA) , College Name, Department, Current Semester, WCF Mentor, WCF E-Mail ID, Batch, Stream, College Code, Stream Code, PBL_ID, Tr.No) VALUES ('21IT059', 'Vishal K', 'vishuvishal00001@gmail.com', '81', '85.6', '8', 'Nandha Engineering College, Erode', 'IT', 'VI', 'A.Bharathi', 'bharathi.a@nandhaengg.org', 'Batch 1', 'JAVA Full Stack', '125', 'J', 'J_1250159', 'TNext_FY25_125_01_J');
INSERT INTO tableName (Student Roll Num, Student Name, StudentEmailID, 10th %, 12th %, Current  % ( or CGPA) , College Name, Department, Current Semester, WCF Mentor, WCF E-Mail ID, Batch, Stream, College Code, Stream Code, PBL_ID, Tr.No) VALUES ('21IT058', 'Vishal.D', 'vishaldeva98@gmail.com', '63', '75', '7', 'Nandha Engineering College, Erode', 'IT', 'VI', 'A.Bharathi', 'bharathi.a@nandhaengg.org', 'Batch 1', 'JAVA Full Stack', '125', 'J', 'J_1250160', 'TNext_FY25_125_01_J');
